https://github.com/miladlink/TinyYoloV2

https://github.com/eriklindernoren/PyTorch-YOLOv3


# Setup

In [1]:
!python filter_sample_json.py

Found 20 images in the 'data/COCO2017/images/valid_sample' directory.
Successfully loaded original JSON file: 'data/COCO2017/annotations/instances_val2017.json'.
After filtering, 20 image annotations will be kept.
After filtering, 143 annotations will be kept.
Filtering complete! The new JSON file has been saved to: 'data/COCO2017/annotations/instances_val2017_modified_sample.json'
Found 20 images in the 'data/COCO2017/images/train_sample' directory.
Successfully loaded original JSON file: 'data/COCO2017/annotations/instances_train2017.json'.
After filtering, 20 image annotations will be kept.
After filtering, 89 annotations will be kept.
Filtering complete! The new JSON file has been saved to: 'data/COCO2017/annotations/instances_train2017_modified_sample.json'


# Helper functions


In [4]:
def xyxy2xywh(x):
    # Convert nx4 boxes from [x1, y1, x2, y2] to [x, y, w, h] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[..., 0] = (x[..., 0] + x[..., 2]) / 2  # x center
    y[..., 1] = (x[..., 1] + x[..., 3]) / 2  # y center
    y[..., 2] = x[..., 2] - x[..., 0]  # width
    y[..., 3] = x[..., 3] - x[..., 1]  # height
    return y

def xywh2xyxy(x):
    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[..., 0] = x[..., 0] - x[..., 2] / 2  # top left x
    y[..., 1] = x[..., 1] - x[..., 3] / 2  # top left y
    y[..., 2] = x[..., 0] + x[..., 2] / 2  # bottom right x
    y[..., 3] = x[..., 1] + x[..., 3] / 2  # bottom right y
    return y

def yolo2json(boxes, img_copy, image_id):
    # * put into coco format of x_min,y_min, width, height, bbox_conf, cls
    # yolo format is x_center, y_center, w, h, bbox_conf, cls_conf, cls
    predictions = []
    for box in boxes:
        x_center, y_center, w, h, conf, cls = box
        x_min = max(0, (x_center - w / 2) * img_copy.shape[3])
        y_min = max(0, (y_center - h / 2) * img_copy.shape[2])
        width = min(img_copy.shape[3], w * img_copy.shape[3])
        height = min(img_copy.shape[2], h * img_copy.shape[2])
        # print(x_min,y_min, width, height, bbox_conf, cls)
        predictions.append({
            'image_id': image_id,
            'category_id': int(id_list[int(cls)]) if modelv == 3 else int(cls),
            'bbox': [int(x_min), int(y_min), int(width), int(height)],
            'score': round(float(conf),2)
        })
    return predictions

def nms2yolo(boxes, img_copy):
    boxes = xyxy2xywh(boxes) # convert from coco to yolo: nms returns nx6 (x1, y1, x2, y2, conf, cls), change to center coordinates [x_center, y_center, width, height]
    boxes[:,0] = boxes[:,0]/img_copy.shape[3]
    boxes[:,1] = boxes[:,1]/img_copy.shape[2]
    boxes[:,2] = boxes[:,2]/img_copy.shape[3]
    boxes[:,3] = boxes[:,3]/img_copy.shape[2]
    return boxes

def saveImageWithBoxes(images, boxes, class_names, fileName):
    to_pil = transforms.ToPILImage()
    pil_image = to_pil(images.squeeze())
    pred_img = plot_boxes(pil_image, boxes, None, class_names)
    pred_img.save(fileName)

def saveImage(img):
    # * just for sanity check, output image. put the dim 3 at the back
    imageN = img.clone().detach()
    imageN = imageN.cpu().squeeze().permute(1, 2, 0).numpy()
    imageN = cv2.cvtColor(imageN, cv2.COLOR_RGB2BGR)
    # print(imageN.shape)
    cv2.imwrite("data/results/mygraph.jpg", imageN*255)

def getOneIter(dataloader):
    images, annotations = next(iter(dataloader))
    np.set_printoptions(linewidth=500)
    np.set_printoptions(suppress=True)
    print("dataloader out")
    print(annotations[0].numpy())


def imgToGreyscale(img):
    if img.shape[0] != 3:
        raise ValueError("Input tensor must have shape [3, H, W].")
    grayscale = 0.299 * img[0] + 0.587 * img[1] + 0.114 * img[2]
    grayscale_tensor = grayscale.unsqueeze(0).repeat(3, 1, 1)
    return grayscale_tensor

# Libraries

In [2]:
import os
import time
from PIL import Image
import numpy as np
import json
import cv2
from tqdm import tqdm
# import skimage.io as io
# import matplotlib.pyplot as plt
from pycocotools.coco import COCO
import torch
import torch.optim as optim
import torchvision
from torchvision import transforms
import torchvision.transforms as transforms
from torchvision.datasets.coco import CocoDetection
from torch.utils.data import DataLoader

from utils.YOLOv2 import *
from models.YOLOv3 import load_model
from attacks.FGSM import FGSM
from attacks.PGD import PGD
from attacks.CW import CW
from attacks.noise import Noise
from detect import detect_image
from utils.loss import compute_loss
from utils.utils import load_classes, rescale_boxes, non_max_suppression, print_environment_info
from utils.augmentations import TRANSFORM_TRAIN, TRANSFORM_VAL
from utils.transforms import DEFAULT_TRANSFORMS, Resize, ResizeEval

In [5]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

os.environ['CUDA_LAUNCH_BLOCKING'] = '1' # reset CUDA debugging environment variable
os.environ['TORCH_USE_CUDA_DSA'] = '1' # enable CUDA DSA for debugging

# Model import

In [7]:
modelv = 3
img_size=416

# if modelv == 2:
#     model = load_model_v2(weights = './weights/yolov2-tiny-voc.weights').to(device)
#     class_names = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'TVmonitor']
#     root_train = "./data/VOC2007/JPEGImages"
#     annFile_train = "./data/VOC2007/annotations/train.json"
#     root_val = "./data/VOC2007/JPEGImages"
#     annFile_val = "./data/VOC2007/annotations/val.json"

if modelv == 3:
    model = load_model("./config/yolov3.cfg", "./weights/yolov3.weights")
    class_names = ['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
    id_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 67, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90])
    root_train = "./data/COCO2017/images/train_sample"
    annFile_train = "./data/COCO2017/annotations/instances_train2017_modified_sample.json"
    root_val = "./data/COCO2017/images/valid_sample"
    annFile_val = "./data/COCO2017/annotations/instances_val2017_modified_sample.json"

else:
    print("invalid model number!")

# COCO loader

create dataloader (make different train and val later)

In [8]:
# coco_dataset_train = CocoDetection(root=root_train, annFile=annFile_train, transform=TRANSFORM_TRAIN_IMG, target_transform=TRANSFORM_TRAIN_TARGET)
# coco_dataset_train = CocoDetection(root=root_train, annFile=annFile_train, transforms=TRANSFORM_TRAIN)
coco_dataset_val = CocoDetection(root=root_val, annFile=annFile_val, transforms=TRANSFORM_VAL)
# coco_dataset_eval = CocoDetection(root=root_val, annFile=annFile_val, transform=transforms.Compose([transforms.ToTensor(),]))

def collate_fn(batch):
    return tuple(zip(*batch))

# Create a DataLoader for your COCO dataset
train_loader = DataLoader(coco_dataset_val, batch_size=4, shuffle=True, collate_fn=collate_fn) # multiple images per batch
val_loader = DataLoader(coco_dataset_val, batch_size=1, shuffle=True, collate_fn=collate_fn)
# one per batch
# cocoeval_loader = DataLoader(coco_dataset_eval, batch_size=1, shuffle=True, collate_fn=collate_fn) # original images without transformatios


loading annotations into memory...
Done (t=0.01s)
creating index...
index created!


In [9]:
getOneIter(val_loader) # print targets

dataloader out
[[139.          64.           0.37028126   0.38985937   0.03859375   0.10859374]
 [139.          72.           0.06382031   0.4293125    0.12764063   0.14823439]
 [139.          72.           0.87064061   0.49404687   0.12710943   0.12301562]
 [139.          62.           0.56090627   0.50789062   0.0875       0.16067188]
 [139.          62.           0.45420313   0.50781249   0.0966094    0.15387499]
 [139.          62.           0.645625     0.51564063   0.04714065   0.127125  ]
 [139.          62.           0.49593749   0.50975001   0.03371878   0.01810937]
 [139.           1.           0.645        0.41345313   0.08289065   0.21564063]
 [139.           1.           0.60067186   0.43626562   0.02362499   0.05584376]
 [139.          78.           0.80034378   0.48867187   0.02303128   0.02495313]
 [139.          82.           0.77046874   0.43959374   0.03170314   0.16923437]
 [139.          84.           0.94495311   0.64514062   0.02240629   0.07142186]
 [139.       

# Adversarial training

In [10]:
eps = 0.05
# attacker = FGSM(model=model, epsilon=0.05)
# attacker = PGD(model=model, epsilon=0.05, epoch=5, lr=0.02)
attacker = CW(model=model, epsilon=eps, lr=eps/3, epoch=5, target=52) # 52 is banana
# attacker = Noise(model=model, epsilon=0.1)


In [11]:
losses = []
epochs = 50
checkpoint_interval = epochs
params = [p for p in model.parameters() if p.requires_grad]
optimizer = optim.Adam(
            params,
            lr=model.hyperparams['learning_rate'],
            weight_decay=model.hyperparams['decay'],
        )

for epoch in range(1, epochs+1):
    print(f"Starting epoch {epoch}")
    lossesEpoch = []

    for batch_idx, (images, targets) in enumerate(tqdm(train_loader)):
        model.train()

        if targets[0].numel() != 0:
            try:
                #* modify inputs to be in proper shape
                images = torch.stack(images) # images.shape is [n, 3, 416, 416] (even if n=1)
                images = images.to(device)

                # modify targets to be in proper shape
                for i, boxes in enumerate(targets): # targets is nx6, (image,class,x,y,w,h)
                    if boxes.ndim == 2:
                        boxes[:, 0] = i # change out image_id to id in batch to conform to compute_loss

                targets = torch.cat(targets, 0).to(device) # from tuples to one tensor
                targets = targets[:, :6]

                # verify class indices range
                class_indices = targets[:, 1].long()
                valid_classes = (class_indices >= 0) & (class_indices < 80)

                if not valid_classes.all():
                    print(f"Warning: Invalid class indices found: {class_indices[~valid_classes]}")
                    # Filter out invalid classes
                    targets = targets[valid_classes]
                    if targets.shape[0] == 0:
                        print("No valid targets after filtering, skipping batch")
                        continue

                # ensure all class indices are long
                targets[:, 1] = targets[:, 1].long()

                print(f"Batch {batch_idx}: targets shape: {targets.shape}, class range: {targets[:, 1].min()}-{targets[:, 1].max()}")

                images_adv = attacker.forward(images, targets) # get adversarial image
                outputsBefore = model(images)
                lossBefore, loss_components = compute_loss(outputsBefore, targets, model)
                outputsAfter = model(images_adv)
                lossAfter, loss_components = compute_loss(outputsAfter, targets, model)
                loss = lossBefore + lossAfter

                lossesEpoch.append(loss.detach().cpu().numpy())
                loss.backward()
                optimizer.step()
                # Reset gradients
                optimizer.zero_grad()

                time.sleep(0.1) # for using noise attack

            except RuntimeError as e:
                print(f"Error in batch {batch_idx}: {e}")
                print(f"Targets shape: {targets.shape if 'targets' in locals() else 'undefined'}")
                if 'targets' in locals():
                    print(f"Class indices: {targets[:, 1].unique()}")
                # clear gradients and continue to next batch
                optimizer.zero_grad()
                torch.cuda.empty_cache()
                continue

        else:
            continue # pics without targets

    if lossesEpoch:
        losses_avg = np.average(lossesEpoch)
        print(f"Epoch {epoch} average loss: {losses_avg}")
        losses.append(losses_avg)

    if epoch % checkpoint_interval == 0:
        checkpoint_path = f"./data/results/checkpoints/yolov3_ckpt_{epoch}.pth"
        print(f"---- Saving checkpoint to: '{checkpoint_path}' ----")
        os.makedirs("./data/results/checkpoints", exist_ok=True)
        torch.save(model.state_dict(), checkpoint_path)

Starting epoch 1


  0%|          | 0/5 [00:00<?, ?it/s]

        86, 86, 86, 86, 88, 88, 88], device='cuda:0')
Batch 0: targets shape: torch.Size([25, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:07,  1.95s/it]

Batch 1: targets shape: torch.Size([26, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:03<00:04,  1.42s/it]

Batch 2: targets shape: torch.Size([12, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:04<00:02,  1.25s/it]

Batch 3: targets shape: torch.Size([34, 6]), class range: 1.0-43.0


 80%|████████  | 4/5 [00:05<00:01,  1.17s/it]

Batch 4: targets shape: torch.Size([19, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:06<00:00,  1.23s/it]


Epoch 1 average loss: 0.8860416412353516
Starting epoch 2


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([26, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([26, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([34, 6]), class range: 1.0-65.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([10, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([20, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 2 average loss: 0.630720317363739
Starting epoch 3


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([12, 6]), class range: 3.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([24, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([14, 6]), class range: 1.0-43.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([22, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([44, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 3 average loss: 0.5437723398208618
Starting epoch 4


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([14, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([27, 6]), class range: 1.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([20, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([24, 6]), class range: 1.0-76.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([31, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 4 average loss: 0.49016493558883667
Starting epoch 5


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([15, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([31, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([20, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([22, 6]), class range: 1.0-54.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([28, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 5 average loss: 0.45970505475997925
Starting epoch 6


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([28, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([33, 6]), class range: 1.0-65.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([17, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([23, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([15, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 6 average loss: 0.4391065537929535
Starting epoch 7


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([17, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([26, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([25, 6]), class range: 1.0-42.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([30, 6]), class range: 1.0-76.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

        82, 84, 84, 85, 86, 86, 86, 86], device='cuda:0')
Batch 4: targets shape: torch.Size([18, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 7 average loss: 0.4208087921142578
Starting epoch 8


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([20, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([30, 6]), class range: 1.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([28, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([25, 6]), class range: 1.0-43.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([13, 6]), class range: 3.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 8 average loss: 0.3963750898838043
Starting epoch 9


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([19, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([22, 6]), class range: 1.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([22, 6]), class range: 1.0-54.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([14, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([39, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 9 average loss: 0.3832319378852844
Starting epoch 10


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([9, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([43, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([20, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([14, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([30, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 10 average loss: 0.3783445954322815
Starting epoch 11


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([20, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([39, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([25, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([17, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

       device='cuda:0')
Batch 4: targets shape: torch.Size([15, 6]), class range: 3.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 11 average loss: 0.3597058653831482
Starting epoch 12


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([16, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([30, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([34, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([10, 6]), class range: 1.0-76.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

       device='cuda:0')
Batch 4: targets shape: torch.Size([26, 6]), class range: 1.0-65.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 12 average loss: 0.33899641036987305
Starting epoch 13


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([15, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([38, 6]), class range: 1.0-78.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([26, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([22, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([15, 6]), class range: 1.0-54.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 13 average loss: 0.33310046792030334
Starting epoch 14


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([26, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([25, 6]), class range: 1.0-42.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([29, 6]), class range: 1.0-79.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([9, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([27, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 14 average loss: 0.3249177038669586
Starting epoch 15


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([15, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([32, 6]), class range: 1.0-78.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([23, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([21, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([25, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 15 average loss: 0.32165879011154175
Starting epoch 16


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([28, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([11, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([26, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([23, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([28, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 16 average loss: 0.3132668137550354
Starting epoch 17


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([30, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([39, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([25, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([9, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([13, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 17 average loss: 0.3099452555179596
Starting epoch 18


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([25, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([19, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([18, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([25, 6]), class range: 1.0-43.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

       device='cuda:0')
Batch 4: targets shape: torch.Size([29, 6]), class range: 1.0-65.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 18 average loss: 0.2918407917022705
Starting epoch 19


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([17, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([15, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([28, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([44, 6]), class range: 1.0-78.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([12, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 19 average loss: 0.2851462662220001
Starting epoch 20


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([27, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([8, 6]), class range: 3.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([18, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([21, 6]), class range: 1.0-76.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([42, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 20 average loss: 0.2799306809902191
Starting epoch 21


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([28, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([27, 6]), class range: 1.0-65.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([16, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([20, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([25, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 21 average loss: 0.27236607670783997
Starting epoch 22


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([36, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([8, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([26, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([19, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([27, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 22 average loss: 0.269856721162796
Starting epoch 23


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([12, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([39, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([27, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([16, 6]), class range: 1.0-78.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([22, 6]), class range: 1.0-54.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 23 average loss: 0.26300573348999023
Starting epoch 24


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([29, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([23, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([18, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([34, 6]), class range: 1.0-78.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([12, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 24 average loss: 0.2575305104255676
Starting epoch 25


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([18, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([24, 6]), class range: 1.0-78.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([33, 6]), class range: 1.0-65.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([13, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([28, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 25 average loss: 0.24966493248939514
Starting epoch 26


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([10, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([44, 6]), class range: 1.0-78.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([16, 6]), class range: 1.0-65.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([29, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([17, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 26 average loss: 0.24588903784751892
Starting epoch 27


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([38, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([12, 6]), class range: 1.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([17, 6]), class range: 1.0-79.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([22, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([27, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 27 average loss: 0.24599239230155945
Starting epoch 28


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([29, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([18, 6]), class range: 1.0-65.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([19, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([36, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([14, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 28 average loss: 0.24901041388511658
Starting epoch 29


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([23, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([15, 6]), class range: 1.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([31, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([33, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

       device='cuda:0')
Batch 4: targets shape: torch.Size([14, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 29 average loss: 0.24135372042655945
Starting epoch 30


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([21, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([32, 6]), class range: 1.0-78.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([22, 6]), class range: 1.0-43.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([27, 6]), class range: 1.0-76.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([14, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 30 average loss: 0.23050883412361145
Starting epoch 31


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([46, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([11, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([22, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([22, 6]), class range: 1.0-43.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([15, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 31 average loss: 0.23025520145893097
Starting epoch 32


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([12, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([16, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([32, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([36, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([20, 6]), class range: 1.0-65.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 32 average loss: 0.22981193661689758
Starting epoch 33


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([24, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([14, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([16, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([32, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([30, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 33 average loss: 0.22124631702899933
Starting epoch 34


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([22, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([10, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([28, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([28, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([28, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 34 average loss: 0.22346317768096924
Starting epoch 35


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([27, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([35, 6]), class range: 1.0-43.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([20, 6]), class range: 1.0-79.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([20, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

       device='cuda:0')
Batch 4: targets shape: torch.Size([14, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 35 average loss: 0.21264652907848358
Starting epoch 36


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([25, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([28, 6]), class range: 1.0-65.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([12, 6]), class range: 1.0-42.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([35, 6]), class range: 1.0-78.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

       device='cuda:0')
Batch 4: targets shape: torch.Size([16, 6]), class range: 1.0-79.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 36 average loss: 0.20418024063110352
Starting epoch 37


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([32, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([32, 6]), class range: 1.0-43.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([24, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([10, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([18, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 37 average loss: 0.20479783415794373
Starting epoch 38


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([21, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([33, 6]), class range: 1.0-13.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([6, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([21, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([35, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 38 average loss: 0.2015748918056488
Starting epoch 39


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([34, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([21, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

       device='cuda:0')
Batch 2: targets shape: torch.Size([27, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([14, 6]), class range: 1.0-54.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([20, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 39 average loss: 0.19767166674137115
Starting epoch 40


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([35, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([12, 6]), class range: 17.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([17, 6]), class range: 1.0-79.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([16, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([36, 6]), class range: 1.0-43.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 40 average loss: 0.1998085081577301
Starting epoch 41


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([22, 6]), class range: 1.0-43.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([24, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([25, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([26, 6]), class range: 1.0-79.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

        86, 86, 86, 86], device='cuda:0')
Batch 4: targets shape: torch.Size([19, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 41 average loss: 0.19196997582912445
Starting epoch 42


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([20, 6]), class range: 1.0-78.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([21, 6]), class range: 1.0-65.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([16, 6]), class range: 1.0-79.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([24, 6]), class range: 1.0-76.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([35, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 42 average loss: 0.1834985315799713
Starting epoch 43


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([21, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([24, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([14, 6]), class range: 1.0-35.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([29, 6]), class range: 1.0-43.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([28, 6]), class range: 1.0-76.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 43 average loss: 0.1787392795085907
Starting epoch 44


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([9, 6]), class range: 1.0-65.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

       device='cuda:0')
Batch 1: targets shape: torch.Size([14, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([24, 6]), class range: 1.0-76.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([37, 6]), class range: 1.0-78.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([32, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 44 average loss: 0.17896291613578796
Starting epoch 45


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([36, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([13, 6]), class range: 1.0-76.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

        84, 84, 84, 84], device='cuda:0')
Batch 2: targets shape: torch.Size([32, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

Batch 3: targets shape: torch.Size([21, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([14, 6]), class range: 1.0-54.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 45 average loss: 0.17199119925498962
Starting epoch 46


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([36, 6]), class range: 1.0-77.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([26, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([22, 6]), class range: 1.0-79.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([16, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([16, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 46 average loss: 0.1730649173259735
Starting epoch 47


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([14, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([19, 6]), class range: 1.0-77.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([34, 6]), class range: 1.0-54.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([24, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

        84, 84, 84, 84, 84, 84, 84], device='cuda:0')
Batch 4: targets shape: torch.Size([25, 6]), class range: 1.0-78.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 47 average loss: 0.1707795113325119
Starting epoch 48


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([21, 6]), class range: 1.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.04s/it]

Batch 1: targets shape: torch.Size([16, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([28, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([27, 6]), class range: 1.0-65.0


 80%|████████  | 4/5 [00:04<00:01,  1.05s/it]

Batch 4: targets shape: torch.Size([24, 6]), class range: 1.0-65.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 48 average loss: 0.14506137371063232
Starting epoch 49


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([16, 6]), class range: 1.0-79.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([26, 6]), class range: 1.0-78.0


 40%|████      | 2/5 [00:02<00:03,  1.05s/it]

Batch 2: targets shape: torch.Size([39, 6]), class range: 1.0-77.0


 60%|██████    | 3/5 [00:03<00:02,  1.05s/it]

       device='cuda:0')
Batch 3: targets shape: torch.Size([11, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([24, 6]), class range: 1.0-65.0


100%|██████████| 5/5 [00:05<00:00,  1.05s/it]


Epoch 49 average loss: 0.1323242336511612
Starting epoch 50


  0%|          | 0/5 [00:00<?, ?it/s]

       device='cuda:0')
Batch 0: targets shape: torch.Size([8, 6]), class range: 17.0-76.0


 20%|██        | 1/5 [00:01<00:04,  1.05s/it]

Batch 1: targets shape: torch.Size([11, 6]), class range: 1.0-79.0


 40%|████      | 2/5 [00:02<00:03,  1.04s/it]

Batch 2: targets shape: torch.Size([34, 6]), class range: 1.0-78.0


 60%|██████    | 3/5 [00:03<00:02,  1.04s/it]

Batch 3: targets shape: torch.Size([26, 6]), class range: 1.0-77.0


 80%|████████  | 4/5 [00:04<00:01,  1.04s/it]

Batch 4: targets shape: torch.Size([37, 6]), class range: 1.0-77.0


100%|██████████| 5/5 [00:05<00:00,  1.04s/it]


Epoch 50 average loss: 0.13043507933616638
---- Saving checkpoint to: './data/results/checkpoints/yolov3_ckpt_50.pth' ----


## Load adversarial trained model

In [12]:
modelv = 3
img_size=416

if modelv == 2:
    model = load_model_v2(weights = './weights/yolov2-tiny-voc.weights').to(device)
    class_names = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'TVmonitor']
    root_train = "./data/VOC2007/JPEGImages"
    annFile_train = "./data/VOC2007/annotations/train.json"
    root_val = "./data/VOC2007/JPEGImages"
    annFile_val = "./data/VOC2007/annotations/val.json"

elif modelv == 3:
    model = load_model("./config/yolov3.cfg", "./data/results/checkpoints/yolov3_ckpt_50.pth")
    class_names = ['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
    id_list = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 27, 28, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 67, 70, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 84, 85, 86, 87, 88, 89, 90])
    root_train = "./data/COCO2017/images/train_sample"
    annFile_train = "./data/COCO2017/annotations/instances_train2017_modified_sample.json"
    root_val = "./data/COCO2017/images/valid_sample"
    annFile_val = "./data/COCO2017/annotations/instances_val2017_modified_sample.json"

else:
    print("invalid model number!")

# Attack Evaluation

In [10]:
attackImage = 0 # variable for saving attack image, run this first, change pruning ratio (attack), 
#don't run this and only run below cells

### NOTE: Attacker was defined here.

In [13]:
predictionsBefore = []
predictionsAfter = []
lossesBefore = []
lossesAfter = []
mode = "image" # need different modes if i want to save image or output prediction json
# mode = "json"
image_ids= [139, 285, 632, 724, 776, 785, 802, 872, 885, 1000,
            1268, 1296, 1353,1425, 1490, 1503, 1532, 1584, 1675, 1761]

os.makedirs("./data/results/images", exist_ok=True)

for i, (images, targets) in enumerate(tqdm(val_loader)):
    if targets[0].numel() != 0:
        with torch.no_grad():
            #* modify inputs to be in proper shape
            images = torch.stack(images) # images.shape is [n, 3, 416, 416] (even if n=1)
            images = images.to(device)
            image_id = int(targets[0][0,0].cpu().numpy()) # assume 1 image
            if image_id not in image_ids: continue # for when we want outputs of specific images
            for i, boxes in enumerate(targets): # targets is nx6, (image,class,x,y,w,h)
                if boxes.ndim == 2: boxes[:, 0] = i # change out image_id to id in batch to conform to compute_loss. this is normally done in ListDataset -> collate_fn. the id now starts at 0 for each image
            targets = torch.cat(targets, 0).to(device) # from tuples to one tensor
            # originalImageSize = targets[0, 6:].cpu().numpy() # original image shape, assume one image per batch - NOT available in json format
            img_info = coco_dataset_val.coco.imgs[image_id]
            originalImageSize = (img_info['height'], img_info['width'])
            targets = targets[:, :6]

            # print debugging information
            print(f"Image ID: {image_id}")
            print(f"Original targets shape: {targets.shape}")
            print(f"Targets data:")
            print(targets)
            print(f"Class indices: {targets[:, 1]}")
            print(f"Class range: {targets[:, 1].min()} - {targets[:, 1].max()}")

            # check mapping of class indices
            original_classes = targets[:, 1].clone()
            print(f"Original class IDs: {original_classes}")

            # mapping class indices ([1, 80] to [0, 79] range
            targets[:, 1] = targets[:, 1] - 1

            # verify mapped class indices
            mapped_classes = targets[:, 1]
            print(f"Mapped class IDs: {mapped_classes}")
            print(f"Mapped class range: {mapped_classes.min()} - {mapped_classes.max()}")

            # ensure all classes are in range [0, 79]
            valid_mask = (mapped_classes >= 0) & (mapped_classes < 80)
            if not valid_mask.all():
                print(f"Invalid class indices found: {mapped_classes[~valid_mask]}")
                targets = targets[valid_mask]
                if targets.shape[0] == 0:
                    print("No valid targets after filtering, skipping image")
                    continue
                print(f"Filtered targets shape: {targets.shape}")

            # ensure all class indices are long
            targets[:, 1] = targets[:, 1].long()

            # final validation
            final_classes = targets[:, 1]
            print(f"Final class indices: {final_classes}")
            print(f"Final class range: {final_classes.min()} - {final_classes.max()}")
            print(f"All classes in range [0, 79]: {((final_classes >= 0) & (final_classes < 80)).all()}")

            #* loss
            model.train()
            try:
                outputsBefore = model(images)
                print(f"Model output shapes: {[out.shape for out in outputsBefore]}")

                lossBefore, loss_components = compute_loss(outputsBefore, targets, model)
                lossesBefore.append(lossBefore.cpu().numpy())

                images_adv = attacker.forward(images, targets) # get adversarial image

                outputsAfter = model(images_adv)
                lossAfter, loss_components = compute_loss(outputsAfter, targets, model)
                lossesAfter.append(lossAfter.cpu().numpy())

            except RuntimeError as e:
                print(f"CUDA error occurred: {e}")
                print(f"Error details:")
                print(f"  Targets shape: {targets.shape}")
                print(f"  Class indices: {targets[:, 1]}")
                print(f"  Class unique values: {targets[:, 1].unique()}")
                print(f"  Class data type: {targets[:, 1].dtype}")

                # clean CUDA cache and skip this iteration
                torch.cuda.empty_cache()
                continue

            #* plot
            model.eval()

            # before attack
            outputsBefore = model(images[0].unsqueeze(0))
            boxesBefore = non_max_suppression(outputsBefore, conf_thres=0.3, iou_thres=0.5)[0].numpy()
            if mode == "json":
                boxesBefore = rescale_boxes(boxesBefore, img_size, originalImageSize)
            boxesBefore = nms2yolo(boxesBefore, images)
            if mode == "image":
                saveImageWithBoxes(images[0], boxesBefore, class_names, f"./data/results/images/attack_before_{image_id}.jpg")
            if mode == "json":
                predictionsBefore += yolo2json(boxesBefore, images[0].unsqueeze(0), image_id)

            # after attack
            outputsAfter = model(images_adv[0].unsqueeze(0))
            boxesAfter = non_max_suppression(outputsAfter, conf_thres=0.3, iou_thres=0.5)[0].numpy()

            if mode == "json":
                boxesAfter = rescale_boxes(boxesAfter, img_size, originalImageSize)
            boxesAfter = nms2yolo(boxesAfter, images_adv)
            print(boxesAfter)
            if mode == "image":
                saveImageWithBoxes(images_adv[0], boxesAfter, class_names, f"./data/results/images/attack_after_{image_id}.jpg")
            if mode == "json":
                predictionsAfter += yolo2json(boxesAfter, images_adv[0].unsqueeze(0), image_id)

    else: continue # pics without targets

with open(f'./data/results/predictionsBefore.json', 'w') as f:
    json.dump(predictionsBefore, f)
with open(f'./data/results/predictionsAfter.json', 'w') as f:
    json.dump(predictionsAfter, f)
np.savetxt("./data/results/lossesBefore.csv", lossesBefore, delimiter=",")
np.savetxt("./data/results/lossesAfter.csv", lossesAfter, delimiter=",")

  0%|          | 0/20 [00:00<?, ?it/s]

Image ID: 776
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[ 0.0000, 88.0000,  0.2185,  0.2280,  0.4370,  0.4561],
        [ 0.0000, 88.0000,  0.2089,  0.4347,  0.4179,  0.5540],
        [ 0.0000, 88.0000,  0.3139,  0.2174,  0.5191,  0.4348],
        [ 0.0000, 65.0000,  0.2506,  0.2501,  0.5011,  0.5001]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([88., 88., 88., 65.], device='cuda:0', dtype=torch.float64)
Class range: 65.0 - 88.0
Original class IDs: tensor([88., 88., 88., 65.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([87., 87., 87., 64.], device='cuda:0', dtype=torch.float64)
Mapped class range: 64.0 - 87.0
Invalid class indices found: tensor([87., 87., 87.], device='cuda:0', dtype=torch.float64)
Filtered targets shape: torch.Size([1, 6])
Final class indices: tensor([64.], device='cuda:0', dtype=torch.float64)
Final class range: 64.0 - 64.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13,

  5%|▌         | 1/20 [00:00<00:13,  1.40it/s]

[[ 0.24628893  0.25053173  0.5628484   0.48615006  0.866558   65.        ]]
Image ID: 1353
Original targets shape: torch.Size([7, 6])
Targets data:
tensor([[0.0000, 7.0000, 0.2566, 0.6472, 0.3798, 0.2786],
        [0.0000, 1.0000, 0.5532, 0.3090, 0.1330, 0.2582],
        [0.0000, 1.0000, 0.4218, 0.2730, 0.1510, 0.1052],
        [0.0000, 1.0000, 0.4012, 0.3962, 0.2561, 0.3691],
        [0.0000, 1.0000, 0.2482, 0.4277, 0.2334, 0.2858],
        [0.0000, 1.0000, 0.3919, 0.3611, 0.1521, 0.1454],
        [0.0000, 1.0000, 0.5013, 0.3656, 0.0640, 0.1255]], device='cuda:0',
       dtype=torch.float64)
Class indices: tensor([7., 1., 1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)
Class range: 1.0 - 7.0
Original class IDs: tensor([7., 1., 1., 1., 1., 1., 1.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([6., 0., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float64)
Mapped class range: 0.0 - 6.0
Final class indices: tensor([6., 0., 0., 0., 0., 0., 0.], device='cud

 10%|█         | 2/20 [00:01<00:11,  1.53it/s]

[[0.25814205 0.64033455 0.37286487 0.2736571  0.8980994  7.        ]
 [0.2498173  0.41363814 0.25729477 0.3360426  0.8600531  1.        ]
 [0.40557316 0.4068589  0.23189522 0.3464467  0.71436197 1.        ]
 [0.4122262  0.28110462 0.17381074 0.2162513  0.6039488  1.        ]
 [0.5527383  0.32889017 0.14137062 0.2737915  0.6017086  1.        ]
 [0.3997695  0.3620777  0.14920124 0.19350955 0.3832554  1.        ]
 [0.42722198 0.27515274 0.10252689 0.08916923 0.33047086 1.        ]]
Image ID: 1425
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[ 0.0000, 54.0000,  0.1973,  0.3890,  0.3946,  0.3408],
        [ 0.0000, 51.0000,  0.7605,  0.3852,  0.2395,  0.3139]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([54., 51.], device='cuda:0', dtype=torch.float64)
Class range: 51.0 - 54.0
Original class IDs: tensor([54., 51.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([53., 50.], device='cuda:0', dtype=torch.float64)
Mapped class range: 5

 15%|█▌        | 3/20 [00:01<00:11,  1.53it/s]

[[ 0.76138604  0.38860303  0.19070362  0.38324115  0.89500487 51.        ]
 [ 0.18898322  0.3935706   0.37937158  0.40861753  0.89331335 54.        ]]
Image ID: 139
Original targets shape: torch.Size([20, 6])
Targets data:
tensor([[0.0000e+00, 6.4000e+01, 3.7028e-01, 3.8986e-01, 3.8594e-02, 1.0859e-01],
        [0.0000e+00, 7.2000e+01, 6.3820e-02, 4.2931e-01, 1.2764e-01, 1.4823e-01],
        [0.0000e+00, 7.2000e+01, 8.7064e-01, 4.9405e-01, 1.2711e-01, 1.2302e-01],
        [0.0000e+00, 6.2000e+01, 5.6091e-01, 5.0789e-01, 8.7500e-02, 1.6067e-01],
        [0.0000e+00, 6.2000e+01, 4.5420e-01, 5.0781e-01, 9.6609e-02, 1.5387e-01],
        [0.0000e+00, 6.2000e+01, 6.4562e-01, 5.1564e-01, 4.7141e-02, 1.2713e-01],
        [0.0000e+00, 6.2000e+01, 4.9594e-01, 5.0975e-01, 3.3719e-02, 1.8109e-02],
        [0.0000e+00, 1.0000e+00, 6.4500e-01, 4.1345e-01, 8.2891e-02, 2.1564e-01],
        [0.0000e+00, 1.0000e+00, 6.0067e-01, 4.3627e-01, 2.3625e-02, 5.5844e-02],
        [0.0000e+00, 7.8000e+01, 8.0034

 20%|██        | 4/20 [00:02<00:12,  1.33it/s]

[[ 0.6408454   0.5205336   0.0819664   0.1182964   0.8874001  62.        ]
 [ 0.44701993  0.49798954  0.14831947  0.15004884  0.84969336 62.        ]
 [ 0.56602466  0.5088222   0.10927802  0.14846744  0.84615666 62.        ]
 [ 0.63698924  0.41006184  0.09998648  0.23278625  0.8372624   1.        ]
 [ 0.5208372   0.5134133   0.14410943  0.13591179  0.63308716 67.        ]
 [ 0.49242896  0.51132745  0.12998119  0.13859902  0.5728415  62.        ]
 [ 0.06121565  0.4295867   0.12723646  0.15045452  0.44326052 72.        ]
 [ 0.6087314   0.51570344  0.09478088  0.13500932  0.4277108  62.        ]]
Image ID: 1675
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[ 0.0000, 17.0000,  0.2500,  0.1881,  0.5000,  0.3762],
        [ 0.0000, 76.0000,  0.2465,  0.6997,  0.4930,  0.1652]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([17., 76.], device='cuda:0', dtype=torch.float64)
Class range: 17.0 - 76.0
Original class IDs: tensor([17., 76.], device='cuda:0', 

 25%|██▌       | 5/20 [00:03<00:10,  1.39it/s]

[[ 0.24962309  0.18614051  0.49201536  0.3521345   0.9670145  17.        ]
 [ 0.24082261  0.69762284  0.6896382   0.13963391  0.8013557  76.        ]]
Image ID: 1296
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[0.0000e+00, 7.7000e+01, 6.3353e-01, 2.2403e-01, 1.1206e-01, 2.1141e-01],
        [0.0000e+00, 8.5000e+01, 7.4614e-01, 6.3791e-01, 2.7391e-02, 2.5953e-02],
        [0.0000e+00, 1.0000e+00, 2.5241e-01, 2.4899e-01, 5.0481e-01, 4.9798e-01],
        [0.0000e+00, 1.0000e+00, 5.7600e-01, 1.0311e-01, 2.2962e-01, 2.0623e-01]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([77., 85.,  1.,  1.], device='cuda:0', dtype=torch.float64)
Class range: 1.0 - 85.0
Original class IDs: tensor([77., 85.,  1.,  1.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([76., 84.,  0.,  0.], device='cuda:0', dtype=torch.float64)
Mapped class range: 0.0 - 84.0
Invalid class indices found: tensor([84.], device='cuda:0', dtype=torch.float64)
Filtered targ

 30%|███       | 6/20 [00:04<00:09,  1.42it/s]

[[ 0.24871683  0.24937211  0.52619016  0.47184607  0.94432956  1.        ]
 [ 0.6326236   0.22254334  0.1027112   0.20423287  0.8799687  77.        ]
 [ 0.5687354   0.10473894  0.23536943  0.20515412  0.8418447   1.        ]
 [ 0.6324056   0.22320645  0.09142549  0.10938637  0.57196647 77.        ]]
Image ID: 1532
Original targets shape: torch.Size([8, 6])
Targets data:
tensor([[0.0000, 3.0000, 0.0472, 0.7026, 0.0944, 0.1601],
        [0.0000, 3.0000, 0.7836, 0.7461, 0.0779, 0.0711],
        [0.0000, 3.0000, 0.3134, 0.7523, 0.0510, 0.0410],
        [0.0000, 3.0000, 0.1659, 0.7120, 0.1236, 0.0931],
        [0.0000, 8.0000, 0.3525, 0.7363, 0.0307, 0.0244],
        [0.0000, 3.0000, 0.6662, 0.7495, 0.1004, 0.0857],
        [0.0000, 3.0000, 0.6340, 0.7531, 0.0398, 0.0435],
        [0.0000, 3.0000, 0.3516, 0.6902, 0.3053, 0.1848]], device='cuda:0',
       dtype=torch.float64)
Class indices: tensor([3., 3., 3., 3., 8., 3., 3., 3.], device='cuda:0', dtype=torch.float64)
Class range: 3.0 - 8.0


 35%|███▌      | 7/20 [00:04<00:08,  1.47it/s]

[[0.04602446 0.7083756  0.09649147 0.14367339 0.97469765 3.        ]
 [0.16347034 0.7102464  0.12920251 0.10676897 0.70736665 3.        ]
 [0.69925016 0.7576217  0.07797212 0.07226694 0.7023958  3.        ]
 [0.67057997 0.7539752  0.0680071  0.06045444 0.58776426 3.        ]
 [0.34488106 0.6822822  0.2633818  0.14599547 0.52544945 3.        ]]
Image ID: 1503
Original targets shape: torch.Size([5, 6])
Targets data:
tensor([[0.0000e+00, 7.3000e+01, 9.9016e-02, 4.3681e-01, 1.9803e-01, 4.2472e-01],
        [0.0000e+00, 7.4000e+01, 3.7800e-01, 6.8116e-01, 1.1803e-01, 6.8937e-02],
        [0.0000e+00, 7.6000e+01, 5.0353e-01, 6.0137e-01, 4.8222e-01, 1.4225e-01],
        [0.0000e+00, 7.2000e+01, 3.9269e-01, 1.6081e-01, 3.4887e-01, 2.7978e-01],
        [0.0000e+00, 7.4000e+01, 9.5484e-01, 6.0747e-01, 4.5000e-02, 3.0188e-02]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([73., 74., 76., 72., 74.], device='cuda:0', dtype=torch.float64)
Class range: 72.0 - 76.0
Original class

 40%|████      | 8/20 [00:05<00:07,  1.52it/s]

[[ 0.09995793  0.4316856   0.18949996  0.4293587   0.95271367 73.        ]
 [ 0.39167207  0.1607078   0.3651655   0.26279896  0.9454014  72.        ]
 [ 0.49874496  0.603939    0.42483667  0.13023703  0.76950675 76.        ]
 [ 0.94895643  0.60823876  0.0709161   0.05136611  0.4995566  74.        ]
 [ 0.37438217  0.6832723   0.10269678  0.05966612  0.4725028  74.        ]]
Image ID: 1490
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[0.0000e+00, 1.0000e+00, 7.0136e-01, 4.3806e-01, 7.9531e-02, 1.9192e-01],
        [0.0000e+00, 4.2000e+01, 5.6128e-01, 6.1295e-01, 3.4202e-01, 2.3484e-02]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([ 1., 42.], device='cuda:0', dtype=torch.float64)
Class range: 1.0 - 42.0
Original class IDs: tensor([ 1., 42.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([ 0., 41.], device='cuda:0', dtype=torch.float64)
Mapped class range: 0.0 - 41.0
Final class indices: tensor([ 0., 41.], device='cuda:0', dtype=

 45%|████▌     | 9/20 [00:06<00:07,  1.56it/s]

[[0.6971312  0.44223097 0.08754129 0.16571999 0.9358879  1.        ]
 [0.6834342  0.43034858 0.07975285 0.11052711 0.34595633 1.        ]]
Image ID: 285
Original targets shape: torch.Size([1, 6])
Targets data:
tensor([[ 0.0000, 23.0000,  0.2506,  0.2740,  0.5011,  0.5481]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([23.], device='cuda:0', dtype=torch.float64)
Class range: 23.0 - 23.0
Original class IDs: tensor([23.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([22.], device='cuda:0', dtype=torch.float64)
Mapped class range: 22.0 - 22.0
Final class indices: tensor([22.], device='cuda:0', dtype=torch.float64)
Final class range: 22.0 - 22.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.Size([1, 3, 26, 26, 85]), torch.Size([1, 3, 52, 52, 85])]


 50%|█████     | 10/20 [00:06<00:06,  1.56it/s]

[[ 0.24673836  0.27460253  0.4654814   0.46975517  0.85514534 23.        ]]
Image ID: 785
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[ 0.0000,  1.0000,  0.4387,  0.2540,  0.3417,  0.5079],
        [ 0.0000, 35.0000,  0.3208,  0.7331,  0.6402,  0.0597]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([ 1., 35.], device='cuda:0', dtype=torch.float64)
Class range: 1.0 - 35.0
Original class IDs: tensor([ 1., 35.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([ 0., 34.], device='cuda:0', dtype=torch.float64)
Mapped class range: 0.0 - 34.0
Final class indices: tensor([ 0., 34.], device='cuda:0', dtype=torch.float64)
Final class range: 0.0 - 34.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.Size([1, 3, 26, 26, 85]), torch.Size([1, 3, 52, 52, 85])]


 55%|█████▌    | 11/20 [00:07<00:05,  1.60it/s]

[[0.433915   0.26496166 0.3128373  0.43425244 0.9280757  1.        ]]
Image ID: 724
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[ 0.0000, 13.0000,  0.3641,  0.1484,  0.2690,  0.2967],
        [ 0.0000,  8.0000,  0.3708,  0.5589,  0.0435,  0.0603],
        [ 0.0000,  3.0000,  0.3805,  0.5344,  0.0258,  0.0163],
        [ 0.0000, 13.0000,  0.5288,  0.5198,  0.0380,  0.0521]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([13.,  8.,  3., 13.], device='cuda:0', dtype=torch.float64)
Class range: 3.0 - 13.0
Original class IDs: tensor([13.,  8.,  3., 13.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([12.,  7.,  2., 12.], device='cuda:0', dtype=torch.float64)
Mapped class range: 2.0 - 12.0
Final class indices: tensor([12.,  7.,  2., 12.], device='cuda:0', dtype=torch.float64)
Final class range: 2.0 - 12.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.Size([1, 3, 26, 26, 85]), torch.Siz

 60%|██████    | 12/20 [00:07<00:04,  1.62it/s]

[[ 0.35803568  0.14809033  0.2893008   0.29180944  0.8559774  13.        ]
 [ 0.5302697   0.52370477  0.06929787  0.07505813  0.6156298  13.        ]
 [ 0.36785764  0.5563991   0.06263205  0.07905623  0.51331687  8.        ]]
Image ID: 872
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[0.0000e+00, 3.7000e+01, 6.5161e-01, 2.6881e-01, 3.0281e-02, 2.5828e-02],
        [0.0000e+00, 1.0000e+00, 2.4103e-01, 2.5730e-01, 4.5617e-01, 5.1460e-01],
        [0.0000e+00, 1.0000e+00, 2.6989e-01, 2.8642e-01, 4.1514e-01, 5.7284e-01],
        [0.0000e+00, 4.0000e+01, 5.9006e-01, 2.4570e-01, 8.9766e-02, 7.1531e-02]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([37.,  1.,  1., 40.], device='cuda:0', dtype=torch.float64)
Class range: 1.0 - 40.0
Original class IDs: tensor([37.,  1.,  1., 40.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([36.,  0.,  0., 39.], device='cuda:0', dtype=torch.float64)
Mapped class range: 0.0 - 39.0
Final class indices:

 65%|██████▌   | 13/20 [00:08<00:04,  1.57it/s]

[[ 0.59125847  0.24000444  0.10841623  0.10114212  0.9718611  40.        ]
 [ 0.25264674  0.26463386  0.4637216   0.54972434  0.94446373  1.        ]]
Image ID: 802
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[ 0.0000, 82.0000,  0.5516,  0.2894,  0.2590,  0.5563],
        [ 0.0000, 79.0000,  0.2204,  0.4517,  0.1978,  0.3618]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([82., 79.], device='cuda:0', dtype=torch.float64)
Class range: 79.0 - 82.0
Original class IDs: tensor([82., 79.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([81., 78.], device='cuda:0', dtype=torch.float64)
Mapped class range: 78.0 - 81.0
Invalid class indices found: tensor([81.], device='cuda:0', dtype=torch.float64)
Filtered targets shape: torch.Size([1, 6])
Final class indices: tensor([78.], device='cuda:0', dtype=torch.float64)
Final class range: 78.0 - 78.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.

 70%|███████   | 14/20 [00:09<00:03,  1.57it/s]

[[ 0.21979314  0.45052466  0.25027677  0.43055937  0.84920657 79.        ]]
Image ID: 1000
Original targets shape: torch.Size([17, 6])
Targets data:
tensor([[0.0000e+00, 4.3000e+01, 7.3547e-02, 5.9873e-01, 7.4109e-02, 1.3644e-01],
        [0.0000e+00, 3.1000e+01, 3.6863e-02, 4.7923e-01, 7.3727e-02, 1.8989e-01],
        [0.0000e+00, 3.1000e+01, 3.0767e-01, 4.7555e-01, 1.0978e-01, 1.8367e-01],
        [0.0000e+00, 1.0000e+00, 1.7994e-01, 3.6270e-01, 1.3005e-01, 3.5689e-01],
        [0.0000e+00, 1.0000e+00, 6.3427e-01, 3.1316e-01, 5.8016e-02, 7.1125e-02],
        [0.0000e+00, 1.0000e+00, 4.1458e-01, 2.7478e-01, 1.3894e-01, 4.9356e-01],
        [0.0000e+00, 1.0000e+00, 3.2692e-01, 3.9787e-01, 1.5567e-01, 3.8919e-01],
        [0.0000e+00, 1.0000e+00, 7.8855e-01, 4.2492e-01, 2.1145e-01, 4.5008e-01],
        [0.0000e+00, 1.0000e+00, 6.4094e-01, 4.5083e-01, 1.7953e-01, 4.2417e-01],
        [0.0000e+00, 1.0000e+00, 5.9508e-01, 3.7486e-01, 1.3819e-01, 4.9883e-01],
        [0.0000e+00, 1.0000e+00

 75%|███████▌  | 15/20 [00:09<00:03,  1.57it/s]

[[ 0.32413277  0.40226305  0.16322547  0.3963695   0.96098894  1.        ]
 [ 0.32276726  0.3774616   0.11561731  0.11117443  0.9520093  27.        ]
 [ 0.176058    0.3590935   0.14242308  0.37764174  0.90012926  1.        ]
 [ 0.629132    0.31546423  0.09722574  0.12758364  0.8761862   1.        ]
 [ 0.2997538   0.4763298   0.13627212  0.19027358  0.87539417 31.        ]
 [ 0.41166604  0.2822511   0.14279197  0.54054976  0.8672063   1.        ]
 [ 0.785725    0.41522938  0.21542431  0.42866713  0.86546254  1.        ]
 [ 0.5926166   0.35163528  0.14615154  0.5100994   0.79955333  1.        ]
 [ 0.08477668  0.4031262   0.12169583  0.37680113  0.78281516  1.        ]
 [ 0.28982347  0.3238156   0.15103348  0.44452673  0.74528337  1.        ]
 [ 0.5169271   0.35421818  0.14655927  0.52410066  0.73113173  1.        ]
 [ 0.63574064  0.2947871   0.13089338  0.2242322   0.71792346  1.        ]
 [ 0.03649232  0.47909772  0.07924391  0.21836662  0.71560466 31.        ]
 [ 0.5495195   0.31828815

 80%|████████  | 16/20 [00:10<00:02,  1.53it/s]

[[0.31222296 0.49921867 0.10150161 0.11190055 0.85215807 1.        ]
 [0.2530797  0.25841048 0.5432155  0.46204394 0.6811628  6.        ]
 [0.13389002 0.6329297  0.05759988 0.09329664 0.58128494 1.        ]
 [0.18249366 0.6440051  0.03944059 0.06453826 0.45217893 1.        ]
 [0.8074903  0.5099461  0.11092861 0.13321026 0.45029336 6.        ]
 [0.71350586 0.5498382  0.04108268 0.04789477 0.42304614 1.        ]
 [0.29521534 0.27522266 0.04736805 0.04626743 0.3757202  1.        ]
 [0.31917816 0.27406678 0.04387663 0.0441695  0.3644193  1.        ]
 [0.48121038 0.26203337 0.06740607 0.05271769 0.3611699  1.        ]
 [0.16199054 0.6424345  0.03844569 0.06562017 0.35410082 1.        ]
 [0.14789186 0.6407182  0.04261428 0.06332108 0.35192454 1.        ]]
Image ID: 1268
Original targets shape: torch.Size([11, 6])
Targets data:
tensor([[0.0000e+00, 1.6000e+01, 3.0127e-01, 5.1688e-01, 1.1677e-01, 5.2234e-02],
        [0.0000e+00, 9.0000e+00, 1.9495e-01, 3.6048e-01, 2.1803e-01, 2.6672e-02],
   

 85%|████████▌ | 17/20 [00:11<00:01,  1.56it/s]

[[ 0.03968342  0.4954449   0.07978478  0.11671235  0.969727    1.        ]
 [ 0.62750125  0.4843157   0.09167257  0.15905857  0.84836537  1.        ]
 [ 0.7811013   0.28334275  0.22273327  0.48168626  0.7959054   1.        ]
 [ 0.4504649   0.2997279   0.18254024  0.09173116  0.69545394  9.        ]
 [ 0.03198533  0.525181    0.03710967  0.0957346   0.567859   27.        ]
 [ 0.01484342  0.4925087   0.03404599  0.12955028  0.4719914   1.        ]
 [ 0.04587852  0.36975533  0.08770205  0.03177467  0.30958036  9.        ]]
Image ID: 1761
Original targets shape: torch.Size([7, 6])
Targets data:
tensor([[0.0000, 5.0000, 0.6066, 0.2178, 0.0800, 0.0684],
        [0.0000, 5.0000, 0.4003, 0.0369, 0.1158, 0.0738],
        [0.0000, 1.0000, 0.1838, 0.9624, 0.0076, 0.0180],
        [0.0000, 1.0000, 0.1723, 0.9630, 0.0113, 0.0153],
        [0.0000, 1.0000, 0.1900, 0.9609, 0.0097, 0.0201],
        [0.0000, 1.0000, 0.2222, 0.9777, 0.0075, 0.0113],
        [0.0000, 1.0000, 0.1989, 0.9642, 0.0115, 0.016

 90%|█████████ | 18/20 [00:11<00:01,  1.57it/s]

[[0.6052438  0.21750265 0.07558078 0.06372547 0.90905726 5.        ]
 [0.400531   0.03687022 0.10748438 0.07293452 0.8731614  5.        ]]
Image ID: 885
Original targets shape: torch.Size([9, 6])
Targets data:
tensor([[0.0000e+00, 1.0000e+00, 4.3330e-01, 4.6248e-01, 2.1889e-01, 3.2534e-01],
        [0.0000e+00, 1.0000e+00, 4.3909e-01, 3.0595e-01, 1.7473e-01, 2.6492e-01],
        [0.0000e+00, 1.0000e+00, 9.3075e-01, 2.0591e-01, 6.7766e-02, 3.5544e-01],
        [0.0000e+00, 1.0000e+00, 6.7922e-01, 1.6614e-01, 5.1234e-02, 1.9797e-02],
        [0.0000e+00, 1.0000e+00, 4.4905e-01, 1.6592e-01, 6.9766e-02, 1.7906e-02],
        [0.0000e+00, 4.3000e+01, 6.2506e-01, 5.8533e-01, 1.2709e-01, 6.2844e-02],
        [0.0000e+00, 1.0000e+00, 8.4669e-01, 1.6833e-01, 1.0287e-01, 1.5812e-02],
        [0.0000e+00, 1.0000e+00, 2.3891e-02, 1.6650e-01, 4.7781e-02, 1.3891e-02],
        [0.0000e+00, 1.0000e+00, 7.8042e-01, 1.6681e-01, 1.1745e-01, 2.0906e-02]],
       device='cuda:0', dtype=torch.float64)
Class 

 95%|█████████▌| 19/20 [00:12<00:00,  1.59it/s]

[[ 0.43184644  0.47404402  0.22707073  0.28129658  0.9231462   1.        ]
 [ 0.4343755   0.30221063  0.20988457  0.2734634   0.90247923  1.        ]
 [ 0.9382465   0.21727699  0.07126632  0.3426139   0.862288    1.        ]
 [ 0.6261136   0.58599544  0.15778647  0.08760757  0.64792347 43.        ]
 [ 0.7761866   0.16462852  0.09634678  0.02652411  0.5526762   1.        ]
 [ 0.67905873  0.16421486  0.07612228  0.02499354  0.40323406  1.        ]]
Image ID: 632
Original targets shape: torch.Size([18, 6])
Targets data:
tensor([[0.0000e+00, 6.5000e+01, 1.5929e-01, 5.3883e-01, 3.1857e-01, 3.2539e-01],
        [0.0000e+00, 6.4000e+01, 2.8650e-01, 3.3525e-01, 9.4969e-02, 1.4436e-01],
        [0.0000e+00, 8.4000e+01, 7.1247e-01, 4.2266e-01, 1.3391e-02, 5.5609e-02],
        [0.0000e+00, 8.4000e+01, 7.0830e-01, 5.1714e-01, 1.2531e-02, 5.3016e-02],
        [0.0000e+00, 8.4000e+01, 6.9494e-01, 5.8692e-01, 8.3125e-03, 6.2000e-02],
        [0.0000e+00, 8.4000e+01, 7.9055e-01, 4.2034e-01, 1.8984e-02

100%|██████████| 20/20 [00:13<00:00,  1.53it/s]

[[ 0.28273922  0.33684498  0.11560316  0.18324375  0.93235534 64.        ]
 [ 0.3772938   0.48228312  0.14452657  0.1388216   0.9258889  62.        ]
 [ 0.15974331  0.53950804  0.36983284  0.369473    0.8869213  65.        ]
 [ 0.28297964  0.33371034  0.10990636  0.092271    0.8733861  64.        ]
 [ 0.54380167  0.44867164  0.14728187  0.24180368  0.8317585  64.        ]]


In [17]:
# predictionsBefore = []
# predictionsAfter = []
# lossesBefore = []
# lossesAfter = []
# # mode = "image" # need different modes if i want to save image or output prediction json
# mode = "json"
# # image_ids= [71711,19221,22192] # output images that i want, 19221 is broccoli, 22192 is dog, 71711 is plane
# # image_ids= [139, 285, 632, 724, 776, 785, 802, 872, 885, 1000,
# #             1268, 1296, 1353,1425, 1490, 1503, 1532, 1584, 1675, 1761] # sample image id
# image_ids = [139]

# os.makedirs("./data/results/images", exist_ok=True)

# for i, (images, targets) in enumerate(tqdm(val_loader)):
#     if targets[0].numel() != 0:
#         with torch.no_grad():
#             #* modify inputs to be in proper shape
#             images = torch.stack(images) # images.shape is [n, 3, 416, 416] (even if n=1)
#             images = images.to(device)
#             image_id = int(targets[0][0,0].cpu().numpy()) # assume 1 image
#             if image_id not in image_ids: continue # for when we want outputs of specific images
#             for i, boxes in enumerate(targets): # targets is nx6, (image,class,x,y,w,h)
#                 if boxes.ndim == 2: boxes[:, 0] = i # change out image_id to id in batch to conform to compute_loss. this is normally done in ListDataset -> collate_fn. the id now starts at 0 for each image
#             targets = torch.cat(targets, 0).to(device) # from tuples to one tensor
#             # originalImageSize = targets[0, 6:].cpu().numpy() # original image shape, assume one image per batch - NOT available in json format
#             img_info = coco_dataset_val.coco.imgs[image_id]
#             originalImageSize = (img_info['height'], img_info['width'])
#             targets = targets[:, :6]

#             #* loss
#             model.train()
#             # start = time.time()
#             outputsBefore = model(images)
#             # end = time.time()
#             # print(end - start)
#             lossBefore, loss_components = compute_loss(outputsBefore, targets, model)
#             lossesBefore.append(lossBefore.cpu().numpy())

#             images_adv = attacker.forward(images, targets) # get adversarial image

#             outputsAfter = model(images_adv)
#             lossAfter, loss_components = compute_loss(outputsAfter, targets, model)
#             lossesAfter.append(lossAfter.cpu().numpy())

#             #* plot
#             model.eval()

#             # ground truth
#             # print(targets) #(ima ge,class,x,y,w,h), the class id starts from 1
#             # nms is (x1, y1, x2, y2, conf, cls), the class id starts from 0
#             # yolo is (x_center, y_center, width, height, conf. cls)

#             # before attack
#             outputsBefore = model(images[0].unsqueeze(0))
#             boxesBefore = non_max_suppression(outputsBefore, conf_thres=0.3, iou_thres=0.5)[0].numpy()
#             if mode == "json":
#                 boxesBefore = rescale_boxes(boxesBefore, img_size, originalImageSize)
#             boxesBefore = nms2yolo(boxesBefore, images)
#             if mode == "image":
#                 saveImageWithBoxes(images[0], boxesBefore, class_names, f"./data/results/images/attack_before_{image_id}.jpg")
#             if mode == "json":
#                 predictionsBefore += yolo2json(boxesBefore, images[0].unsqueeze(0), image_id)

#             # after attack
#             outputsAfter = model(images_adv[0].unsqueeze(0))
#             boxesAfter = non_max_suppression(outputsAfter, conf_thres=0.3, iou_thres=0.5)[0].numpy()


#             if mode == "json":
#                 boxesAfter = rescale_boxes(boxesAfter, img_size, originalImageSize)
#             # print(boxesAfter)
#             boxesAfter = nms2yolo(boxesAfter, images_adv)
#             print(boxesAfter)
#             if mode == "image":
#                 saveImageWithBoxes(images_adv[0], boxesAfter, class_names, f"./data/results/images/attack_after_{image_id}.jpg")

#                 # attackImage = images_adv[0] # for saving the same attack image for different pruning ratios, comment out after save
#                 # saveImageWithBoxes(attackImage, boxesAfter, class_names, f"./data/results/images/pruning/{image_id}/attack_after_99_x.jpg") # plot different pruning ratios with same attack image

#                 # greyscaleAttackImage = imgToGreyscale(attackImage)
#                 # saveImageWithBoxes(greyscaleAttackImage, boxesAfter, class_names, f"./data/results/images/pruning/{image_id}/attack_after_x_grey.jpg") # plot different pruning ratios with same attack image
#             if mode == "json":
#                 predictionsAfter += yolo2json(boxesAfter, images_adv[0].unsqueeze(0), image_id)
#             # time.sleep(0.1) # for using noise attack

#     else: continue # pics without targets
#     # break


# with open(f'./data/results/predictionsBefore.json', 'w') as f:
#     json.dump(predictionsBefore, f)
# with open(f'./data/results/predictionsAfter.json', 'w') as f:
#     json.dump(predictionsAfter, f)
# np.savetxt("./data/results/lossesBefore.csv", lossesBefore, delimiter=",")
# np.savetxt("./data/results/lossesAfter.csv", lossesAfter, delimiter=",")

  0%|          | 0/20 [00:00<?, ?it/s]


RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


In [ ]:
# data = np.loadtxt('./data/results/lossesBefore.csv', delimiter=',')
# average = np.mean(data)
# print("Avg loss before attack:", average)
# data = np.loadtxt('./data/results/lossesAfter.csv', delimiter=',')
# average = np.mean(data)
# print("Avg loss after attack:", average)

# Get mAP

In [ ]:
# from pycocotools.coco import COCO
# from pycocotools.cocoeval import COCOeval

# coco_gld = COCO(annFile_val) # coco
# # if modelv == 2:
# #     coco_rst = coco_gld.loadRes('./data/results/v2predictions.json')
# # elif modelv == 3:
# #     coco_rst = coco_gld.loadRes('./data/results/v3predictions.json')

# coco_rst = coco_gld.loadRes('./data/results/predictionsAfter.json')
# cocoEval = COCOeval(coco_gld, coco_rst, iouType='bbox')
# cocoEval.evaluate()
# cocoEval.accumulate()
# cocoEval.summarize()