https://github.com/miladlink/TinyYoloV2

https://github.com/eriklindernoren/PyTorch-YOLOv3


# Setup (Only use the first time or if the dataset was changed)

In [1]:
# !python filter_sample_json.py

# Libraries

In [2]:
import os
# import time
# from PIL import Image
# import numpy as np
import json
import cv2
from tqdm import tqdm
# import skimage.io as io
# import matplotlib.pyplot as plt
# from pycocotools.coco import COCO
# import torch
import torch.optim as optim
# import torchvision
# from torchvision import transforms
import torchvision.transforms as transforms
from torchvision.datasets.coco import CocoDetection
from torch.utils.data import DataLoader

from utils.YOLOv2 import *
from models.YOLOv3 import load_model
from attacks.FGSM import FGSM
from attacks.PGD import PGD
from attacks.CW import CW
from attacks.noise import Noise
from detect import detect_image
from utils.loss import compute_loss
from utils.utils import load_classes, rescale_boxes, non_max_suppression, print_environment_info
from utils.augmentations import TRANSFORM_TRAIN, TRANSFORM_VAL
from utils.transforms import DEFAULT_TRANSFORMS, Resize, ResizeEval

# Helper functions + vars


In [3]:
def xyxy2xywh(x):
    # Convert nx4 boxes from [x1, y1, x2, y2] to [x, y, w, h] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[..., 0] = (x[..., 0] + x[..., 2]) / 2  # x center
    y[..., 1] = (x[..., 1] + x[..., 3]) / 2  # y center
    y[..., 2] = x[..., 2] - x[..., 0]  # width
    y[..., 3] = x[..., 3] - x[..., 1]  # height
    return y

def xywh2xyxy(x):
    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right
    y = x.clone() if isinstance(x, torch.Tensor) else np.copy(x)
    y[..., 0] = x[..., 0] - x[..., 2] / 2  # top left x
    y[..., 1] = x[..., 1] - x[..., 3] / 2  # top left y
    y[..., 2] = x[..., 0] + x[..., 2] / 2  # bottom right x
    y[..., 3] = x[..., 1] + x[..., 3] / 2  # bottom right y
    return y

def yolo2json(boxes, img_copy, image_id):
    # * put into coco format of x_min,y_min, width, height, bbox_conf, cls
    # yolo format is x_center, y_center, w, h, bbox_conf, cls_conf, cls
    predictions = []
    for box in boxes:
        x_center, y_center, w, h, conf, cls = box
        x_min = max(0, (x_center - w / 2) * img_copy.shape[3])
        y_min = max(0, (y_center - h / 2) * img_copy.shape[2])
        width = min(img_copy.shape[3], w * img_copy.shape[3])
        height = min(img_copy.shape[2], h * img_copy.shape[2])
        # print(x_min,y_min, width, height, bbox_conf, cls)
        predictions.append({
            'image_id': image_id,
            'category_id': int(id_list[int(cls)]) if modelv == 3 else int(cls),
            'bbox': [int(x_min), int(y_min), int(width), int(height)],
            'score': round(float(conf),2)
        })
    return predictions

def nms2yolo(boxes, img_copy):
    boxes = xyxy2xywh(boxes) # convert from coco to yolo: nms returns nx6 (x1, y1, x2, y2, conf, cls), change to center coordinates [x_center, y_center, width, height]
    boxes[:,0] = boxes[:,0]/img_copy.shape[3]
    boxes[:,1] = boxes[:,1]/img_copy.shape[2]
    boxes[:,2] = boxes[:,2]/img_copy.shape[3]
    boxes[:,3] = boxes[:,3]/img_copy.shape[2]
    return boxes

def saveImageWithBoxes(images, boxes, class_names, fileName):
    to_pil = transforms.ToPILImage()
    pil_image = to_pil(images.squeeze())
    pred_img = plot_boxes(pil_image, boxes, None, class_names)
    pred_img.save(fileName)

def saveImage(img):
    # * just for sanity check, output image. put the dim 3 at the back
    imageN = img.clone().detach()
    imageN = imageN.cpu().squeeze().permute(1, 2, 0).numpy()
    imageN = cv2.cvtColor(imageN, cv2.COLOR_RGB2BGR)
    # print(imageN.shape)
    cv2.imwrite("data/results/mygraph.jpg", imageN*255)

def getOneIter(dataloader):
    images, annotations = next(iter(dataloader))
    np.set_printoptions(linewidth=500)
    np.set_printoptions(suppress=True)
    print("dataloader out")
    print(annotations[0].numpy())


def imgToGreyscale(img):
    if img.shape[0] != 3:
        raise ValueError("Input tensor must have shape [3, H, W].")
    grayscale = 0.299 * img[0] + 0.587 * img[1] + 0.114 * img[2]
    grayscale_tensor = grayscale.unsqueeze(0).repeat(3, 1, 1)
    return grayscale_tensor

In [4]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
device

os.environ['CUDA_LAUNCH_BLOCKING'] = '1' # reset CUDA debugging environment variable
os.environ['TORCH_USE_CUDA_DSA'] = '1' # enable CUDA DSA for debugging

In [5]:
epochs = 50 # currently, 100 seems like it works very well
checkpoint_interval = epochs 
# if time is limited then make this smaller, do note that checkpoints are around 270MB per.
modelv = 3
img_size=416

In [6]:
class_names = ['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
id_list = np.array(range(0,80))

# Model import

In [7]:
# if modelv == 2:
#     model = load_model_v2(weights = './weights/yolov2-tiny-voc.weights').to(device)
#     class_names = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'TVmonitor']
#     root_train = "./data/VOC2007/JPEGImages"
#     annFile_train = "./data/VOC2007/annotations/train.json"
#     root_val = "./data/VOC2007/JPEGImages"
#     annFile_val = "./data/VOC2007/annotations/val.json"

if modelv == 3:
    model = load_model("./config/yolov3.cfg", "./weights/yolov3.weights")
    root_train = "./data/COCO2017/images/train_sample"
    annFile_train = "./data/COCO2017/annotations/instances_train2017_modified_sample.json"
    root_val = "./data/COCO2017/images/valid_sample"
    annFile_val = "./data/COCO2017/annotations/instances_val2017_modified_sample.json"

else:
    print("invalid model number!")

# COCO loader

create dataloader (make different train and val later)

In [8]:
# coco_dataset_train = CocoDetection(root=root_train, annFile=annFile_train, transform=TRANSFORM_TRAIN_IMG, target_transform=TRANSFORM_TRAIN_TARGET)
# coco_dataset_train = CocoDetection(root=root_train, annFile=annFile_train, transforms=TRANSFORM_TRAIN)
coco_dataset_train = CocoDetection(root=root_val, annFile=annFile_val, transforms=TRANSFORM_TRAIN)
coco_dataset_val = CocoDetection(root=root_val, annFile=annFile_val, transforms=TRANSFORM_VAL)
# coco_dataset_eval = CocoDetection(root=root_val, annFile=annFile_val, transform=transforms.Compose([transforms.ToTensor(),]))

def collate_fn(batch):
    return tuple(zip(*batch))

# Create a DataLoader for your COCO dataset
train_loader = DataLoader(coco_dataset_val, batch_size=8, shuffle=True, collate_fn=collate_fn) # multiple images per batch
val_loader = DataLoader(coco_dataset_val, batch_size=1, shuffle=True, collate_fn=collate_fn)
# one per batch
# cocoeval_loader = DataLoader(coco_dataset_eval, batch_size=1, shuffle=True, collate_fn=collate_fn) # original images without transformatios


loading annotations into memory...
Done (t=0.00s)
creating index...
index created!
loading annotations into memory...
Done (t=0.00s)
creating index...
index created!


In [9]:
getOneIter(val_loader) # print targets

dataloader out
[[872.          32.           0.65160937   0.26881249   0.03028126   0.02582815]
 [872.           0.           0.24103124   0.15729687   0.45617187   0.71460941]
 [872.           0.           0.26989062   0.19753125   0.41514065   0.75062501]
 [872.          35.           0.59006252   0.24570312   0.0897656    0.07153125]]


# Adversarial training

In [10]:
eps = 0.05
# attacker = FGSM(model=model, epsilon=0.05)
# attacker = PGD(model=model, epsilon=0.05, epoch=5, lr=0.02)
attacker = CW(model=model, epsilon=eps, lr=eps/3, epoch=5, target=52) # 52 is banana
# attacker = Noise(model=model, epsilon=0.1)


In [11]:
losses = []
params = [p for p in model.parameters() if p.requires_grad]
optimizer = optim.Adam(
            params,
            lr=model.hyperparams['learning_rate'],
            weight_decay=model.hyperparams['decay'],
        )

for epoch in range(1, epochs+1):
    print(f"Starting epoch {epoch}")
    lossesEpoch = []

    for batch_idx, (images, targets) in enumerate(tqdm(train_loader)):
        
        model.train()

        if targets[0].numel() != 0:
            try:
                #* modify inputs to be in proper shape
                images = torch.stack(images) # images.shape is [n, 3, 416, 416] (even if n=1)
                images = images.to(device)

                # modify targets to be in proper shape
                for i, boxes in enumerate(targets): # targets is nx6, (image,class,x,y,w,h)
                    if boxes.ndim == 2:
                        boxes[:, 0] = i # change out image_id to id in batch to conform to compute_loss

                targets = torch.cat(targets, 0).to(device) # from tuples to one tensor
                targets = targets[:, :6]
                # class indices are mixed up prior

                # # verify class indices range
                # class_indices = targets[:, 1].long()
                # valid_classes = (class_indices >= 0) & (class_indices < 80)

                # if not valid_classes.all():
                #     print(f"Warning: Invalid class indices found: {class_indices[~valid_classes]}")
                #     # Filter out invalid classes
                #     targets = targets[valid_classes]
                #     if targets.shape[0] == 0:
                #         print("No valid targets after filtering, skipping batch")
                #         continue

                # ensure all class indices are long
                targets[:, 1] = targets[:, 1].long()

                print(f"Batch {batch_idx}: targets shape: {targets.shape}, class range: {targets[:, 1].min()}-{targets[:, 1].max()}")

                images_adv = attacker.forward(images, targets) # get adversarial image
                outputsBefore = model(images)
                lossBefore, loss_components = compute_loss(outputsBefore, targets, model)
                outputsAfter = model(images_adv)
                lossAfter, loss_components = compute_loss(outputsAfter, targets, model)
                loss = lossBefore + lossAfter

                lossesEpoch.append(loss.detach().cpu().numpy())
                loss.backward()
                optimizer.step()
                # Reset gradients
                optimizer.zero_grad()

                time.sleep(0.1) # for using noise attack

            except RuntimeError as e:
                print(f"Error in batch {batch_idx}: {e}")
                print(f"Targets shape: {targets.shape if 'targets' in locals() else 'undefined'}")
                if 'targets' in locals():
                    print(f"Class indices: {targets[:, 1].unique()}")
                # clear gradients and continue to next batch
                optimizer.zero_grad()
                torch.cuda.empty_cache()
                continue

        else:
            continue # pics without targets

    if lossesEpoch:
        losses_avg = np.average(lossesEpoch)
        print(f"Epoch {epoch} average loss: {losses_avg}")
        losses.append(losses_avg)

    if epoch % checkpoint_interval == 0:
        checkpoint_path = f"./data/results/checkpoints/yolov3_ckpt_{epoch}.pth"
        print(f"---- Saving checkpoint to: '{checkpoint_path}' ----")
        os.makedirs("./data/results/checkpoints", exist_ok=True)
        torch.save(model.state_dict(), checkpoint_path)

Starting epoch 1


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([60, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:01<00:04,  1.18s/it]

Batch 1: targets shape: torch.Size([20, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:02,  1.21it/s]

Batch 2: targets shape: torch.Size([35, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:02<00:01,  1.41it/s]

Batch 3: targets shape: torch.Size([10, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.53it/s]

Batch 4: targets shape: torch.Size([18, 6]), class range: 0.0-74.0


100%|██████████| 5/5 [00:03<00:00,  1.45it/s]


Epoch 1 average loss: 0.7761717438697815
Starting epoch 2


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([38, 6]), class range: 0.0-73.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([26, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([16, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([37, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([26, 6]), class range: 0.0-66.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 2 average loss: 0.5338143706321716
Starting epoch 3


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([31, 6]), class range: 0.0-67.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([20, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([25, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([39, 6]), class range: 0.0-73.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([28, 6]), class range: 0.0-74.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 3 average loss: 0.46513280272483826
Starting epoch 4


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([15, 6]), class range: 2.0-77.0


 20%|██        | 1/5 [00:00<00:02,  1.75it/s]

Batch 1: targets shape: torch.Size([31, 6]), class range: 0.0-74.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([29, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([22, 6]), class range: 0.0-72.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([46, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 4 average loss: 0.4401382505893707
Starting epoch 5


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([56, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.74it/s]

Batch 1: targets shape: torch.Size([9, 6]), class range: 0.0-72.0


 40%|████      | 2/5 [00:01<00:01,  1.75it/s]

Batch 2: targets shape: torch.Size([18, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([23, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([37, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 5 average loss: 0.42178258299827576
Starting epoch 6


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([16, 6]), class range: 0.0-72.0


 20%|██        | 1/5 [00:00<00:02,  1.80it/s]

Batch 1: targets shape: torch.Size([27, 6]), class range: 0.0-74.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([28, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([19, 6]), class range: 0.0-37.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([53, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 6 average loss: 0.3939540386199951
Starting epoch 7


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([34, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.79it/s]

Batch 1: targets shape: torch.Size([32, 6]), class range: 0.0-38.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([31, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([19, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.76it/s]

Batch 4: targets shape: torch.Size([27, 6]), class range: 15.0-73.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 7 average loss: 0.38443273305892944
Starting epoch 8


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([12, 6]), class range: 2.0-66.0


 20%|██        | 1/5 [00:00<00:02,  1.79it/s]

Batch 1: targets shape: torch.Size([31, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([23, 6]), class range: 0.0-48.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([30, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([47, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 8 average loss: 0.37206870317459106
Starting epoch 9


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([27, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([22, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([24, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([25, 6]), class range: 0.0-72.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([45, 6]), class range: 0.0-73.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 9 average loss: 0.3531087338924408
Starting epoch 10


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([22, 6]), class range: 0.0-67.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([39, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([40, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([17, 6]), class range: 0.0-72.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([25, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 10 average loss: 0.35070791840553284
Starting epoch 11


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([26, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.75it/s]

Batch 1: targets shape: torch.Size([28, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([42, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([28, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([19, 6]), class range: 0.0-48.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 11 average loss: 0.3343760073184967
Starting epoch 12


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([46, 6]), class range: 0.0-77.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([34, 6]), class range: 0.0-74.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([22, 6]), class range: 0.0-66.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([10, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([31, 6]), class range: 0.0-73.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 12 average loss: 0.3258377015590668
Starting epoch 13


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([15, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.79it/s]

Batch 1: targets shape: torch.Size([15, 6]), class range: 2.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([53, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([36, 6]), class range: 0.0-75.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([24, 6]), class range: 0.0-66.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 13 average loss: 0.3221682012081146
Starting epoch 14


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([18, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([37, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([37, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([35, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([16, 6]), class range: 0.0-66.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 14 average loss: 0.31155091524124146
Starting epoch 15


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([20, 6]), class range: 0.0-66.0


 20%|██        | 1/5 [00:00<00:02,  1.79it/s]

Batch 1: targets shape: torch.Size([19, 6]), class range: 2.0-72.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([24, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([24, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.76it/s]

Batch 4: targets shape: torch.Size([56, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 15 average loss: 0.30731984972953796
Starting epoch 16


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([12, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([31, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([43, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([39, 6]), class range: 0.0-38.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([18, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 16 average loss: 0.30697524547576904
Starting epoch 17


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([37, 6]), class range: 0.0-73.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([24, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([35, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([27, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([20, 6]), class range: 0.0-35.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 17 average loss: 0.29037728905677795
Starting epoch 18


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([35, 6]), class range: 0.0-77.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([12, 6]), class range: 0.0-72.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([34, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([30, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([32, 6]), class range: 0.0-67.0


100%|██████████| 5/5 [00:02<00:00,  1.75it/s]


Epoch 18 average loss: 0.28284648060798645
Starting epoch 19


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([38, 6]), class range: 0.0-73.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([17, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.74it/s]

Batch 2: targets shape: torch.Size([17, 6]), class range: 0.0-66.0


 60%|██████    | 3/5 [00:01<00:01,  1.75it/s]

Batch 3: targets shape: torch.Size([19, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([52, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.75it/s]


Epoch 19 average loss: 0.2848220467567444
Starting epoch 20


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([21, 6]), class range: 0.0-72.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([11, 6]), class range: 0.0-48.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([12, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([52, 6]), class range: 0.0-75.0


 80%|████████  | 4/5 [00:02<00:00,  1.76it/s]

Batch 4: targets shape: torch.Size([47, 6]), class range: 0.0-73.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 20 average loss: 0.27879032492637634
Starting epoch 21


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([24, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([46, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([34, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([13, 6]), class range: 15.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([26, 6]), class range: 0.0-73.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 21 average loss: 0.2793480455875397
Starting epoch 22


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([25, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.74it/s]

Batch 1: targets shape: torch.Size([29, 6]), class range: 2.0-73.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([32, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([32, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([25, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 22 average loss: 0.26635971665382385
Starting epoch 23


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([35, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.75it/s]

Batch 1: targets shape: torch.Size([12, 6]), class range: 0.0-72.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([52, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([14, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([30, 6]), class range: 0.0-66.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 23 average loss: 0.2606826424598694
Starting epoch 24


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([46, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([16, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([15, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([19, 6]), class range: 0.0-48.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([47, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 24 average loss: 0.2579788267612457
Starting epoch 25


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([9, 6]), class range: 0.0-48.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([44, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.79it/s]

Batch 2: targets shape: torch.Size([22, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.79it/s]

Batch 3: targets shape: torch.Size([40, 6]), class range: 0.0-38.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([28, 6]), class range: 0.0-74.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 25 average loss: 0.2584563195705414
Starting epoch 26


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([19, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.80it/s]

Batch 1: targets shape: torch.Size([19, 6]), class range: 0.0-72.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([29, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([32, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([44, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 26 average loss: 0.2517324388027191
Starting epoch 27


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([42, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([24, 6]), class range: 0.0-38.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([18, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([21, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([38, 6]), class range: 0.0-74.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 27 average loss: 0.24354679882526398
Starting epoch 28


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([34, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([19, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([26, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([26, 6]), class range: 0.0-11.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([38, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 28 average loss: 0.24380484223365784
Starting epoch 29


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([34, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.74it/s]

Batch 1: targets shape: torch.Size([42, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([17, 6]), class range: 0.0-66.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([38, 6]), class range: 0.0-73.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([12, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 29 average loss: 0.23794052004814148
Starting epoch 30


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([19, 6]), class range: 0.0-72.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([38, 6]), class range: 0.0-73.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([44, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([28, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([14, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 30 average loss: 0.23248839378356934
Starting epoch 31


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([40, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.74it/s]

Batch 1: targets shape: torch.Size([28, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([37, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([22, 6]), class range: 0.0-38.0


 80%|████████  | 4/5 [00:02<00:00,  1.76it/s]

Batch 4: targets shape: torch.Size([16, 6]), class range: 0.0-66.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 31 average loss: 0.2321069985628128
Starting epoch 32


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([9, 6]), class range: 0.0-66.0


 20%|██        | 1/5 [00:00<00:02,  1.74it/s]

Batch 1: targets shape: torch.Size([53, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.74it/s]

Batch 2: targets shape: torch.Size([24, 6]), class range: 0.0-37.0


 60%|██████    | 3/5 [00:01<00:01,  1.75it/s]

Batch 3: targets shape: torch.Size([20, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.76it/s]

Batch 4: targets shape: torch.Size([37, 6]), class range: 0.0-48.0


100%|██████████| 5/5 [00:02<00:00,  1.75it/s]


Epoch 32 average loss: 0.21944880485534668
Starting epoch 33


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([18, 6]), class range: 2.0-77.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([33, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.73it/s]

Batch 2: targets shape: torch.Size([35, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([31, 6]), class range: 0.0-73.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([26, 6]), class range: 0.0-38.0


100%|██████████| 5/5 [00:02<00:00,  1.75it/s]


Epoch 33 average loss: 0.21930742263793945
Starting epoch 34


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([20, 6]), class range: 0.0-48.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([32, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.75it/s]

Batch 2: targets shape: torch.Size([28, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([32, 6]), class range: 0.0-66.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([31, 6]), class range: 0.0-74.0


100%|██████████| 5/5 [00:02<00:00,  1.75it/s]


Epoch 34 average loss: 0.2137434035539627
Starting epoch 35


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([41, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.75it/s]

Batch 1: targets shape: torch.Size([38, 6]), class range: 0.0-74.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([12, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([27, 6]), class range: 0.0-72.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([25, 6]), class range: 0.0-67.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 35 average loss: 0.21227487921714783
Starting epoch 36


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([27, 6]), class range: 0.0-77.0


 20%|██        | 1/5 [00:00<00:02,  1.70it/s]

Batch 1: targets shape: torch.Size([13, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.75it/s]

Batch 2: targets shape: torch.Size([37, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.73it/s]

Batch 3: targets shape: torch.Size([26, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([40, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.74it/s]


Epoch 36 average loss: 0.20941781997680664
Starting epoch 37


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([30, 6]), class range: 0.0-72.0


 20%|██        | 1/5 [00:00<00:02,  1.79it/s]

Batch 1: targets shape: torch.Size([20, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.79it/s]

Batch 2: targets shape: torch.Size([25, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([50, 6]), class range: 0.0-75.0


 80%|████████  | 4/5 [00:02<00:00,  1.78it/s]

Batch 4: targets shape: torch.Size([18, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 37 average loss: 0.19641627371311188
Starting epoch 38


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([27, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([12, 6]), class range: 0.0-74.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([29, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.79it/s]

Batch 3: targets shape: torch.Size([28, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.79it/s]

Batch 4: targets shape: torch.Size([47, 6]), class range: 0.0-73.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 38 average loss: 0.20290593802928925
Starting epoch 39


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([30, 6]), class range: 0.0-67.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([27, 6]), class range: 45.0-73.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([13, 6]), class range: 0.0-66.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([32, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.79it/s]

Batch 4: targets shape: torch.Size([41, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 39 average loss: 0.20213639736175537
Starting epoch 40


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([13, 6]), class range: 0.0-77.0


 20%|██        | 1/5 [00:00<00:02,  1.80it/s]

Batch 1: targets shape: torch.Size([27, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([46, 6]), class range: 0.0-75.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([39, 6]), class range: 0.0-67.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([18, 6]), class range: 0.0-37.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 40 average loss: 0.1911449134349823
Starting epoch 41


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([11, 6]), class range: 0.0-72.0


 20%|██        | 1/5 [00:00<00:02,  1.79it/s]

Batch 1: targets shape: torch.Size([33, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([26, 6]), class range: 0.0-77.0


 60%|██████    | 3/5 [00:01<00:01,  1.74it/s]

Batch 3: targets shape: torch.Size([26, 6]), class range: 0.0-73.0


 80%|████████  | 4/5 [00:02<00:00,  1.73it/s]

Batch 4: targets shape: torch.Size([47, 6]), class range: 0.0-38.0


100%|██████████| 5/5 [00:02<00:00,  1.74it/s]


Epoch 41 average loss: 0.19167475402355194
Starting epoch 42


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([36, 6]), class range: 0.0-74.0


 20%|██        | 1/5 [00:00<00:02,  1.74it/s]

Batch 1: targets shape: torch.Size([13, 6]), class range: 0.0-66.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([32, 6]), class range: 2.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([27, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([35, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 42 average loss: 0.17175012826919556
Starting epoch 43


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([55, 6]), class range: 0.0-73.0


 20%|██        | 1/5 [00:00<00:02,  1.75it/s]

Batch 1: targets shape: torch.Size([29, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([27, 6]), class range: 0.0-72.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([18, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([14, 6]), class range: 0.0-48.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 43 average loss: 0.17750898003578186
Starting epoch 44


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([25, 6]), class range: 0.0-66.0


 20%|██        | 1/5 [00:00<00:02,  1.75it/s]

Batch 1: targets shape: torch.Size([21, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.75it/s]

Batch 2: targets shape: torch.Size([41, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.76it/s]

Batch 3: targets shape: torch.Size([33, 6]), class range: 0.0-75.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([23, 6]), class range: 0.0-72.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 44 average loss: 0.16024716198444366
Starting epoch 45


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([12, 6]), class range: 0.0-72.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([37, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([35, 6]), class range: 0.0-73.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([35, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([24, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 45 average loss: 0.155530646443367
Starting epoch 46


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([50, 6]), class range: 0.0-73.0


 20%|██        | 1/5 [00:00<00:02,  1.77it/s]

Batch 1: targets shape: torch.Size([15, 6]), class range: 0.0-72.0


 40%|████      | 2/5 [00:01<00:01,  1.79it/s]

Batch 2: targets shape: torch.Size([36, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.78it/s]

Batch 3: targets shape: torch.Size([12, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([30, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.78it/s]


Epoch 46 average loss: 0.14177089929580688
Starting epoch 47


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([41, 6]), class range: 0.0-75.0


 20%|██        | 1/5 [00:00<00:02,  1.78it/s]

Batch 1: targets shape: torch.Size([32, 6]), class range: 0.0-77.0


 40%|████      | 2/5 [00:01<00:01,  1.78it/s]

Batch 2: targets shape: torch.Size([29, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([16, 6]), class range: 0.0-35.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([25, 6]), class range: 0.0-67.0


100%|██████████| 5/5 [00:02<00:00,  1.76it/s]


Epoch 47 average loss: 0.15357239544391632
Starting epoch 48


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([32, 6]), class range: 0.0-67.0


 20%|██        | 1/5 [00:00<00:02,  1.73it/s]

Batch 1: targets shape: torch.Size([38, 6]), class range: 0.0-73.0


 40%|████      | 2/5 [00:01<00:01,  1.74it/s]

Batch 2: targets shape: torch.Size([17, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.73it/s]

Batch 3: targets shape: torch.Size([27, 6]), class range: 0.0-77.0


 80%|████████  | 4/5 [00:02<00:00,  1.74it/s]

Batch 4: targets shape: torch.Size([29, 6]), class range: 0.0-75.0


100%|██████████| 5/5 [00:02<00:00,  1.74it/s]


Epoch 48 average loss: 0.14540188014507294
Starting epoch 49


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([27, 6]), class range: 0.0-38.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([29, 6]), class range: 0.0-73.0


 40%|████      | 2/5 [00:01<00:01,  1.76it/s]

Batch 2: targets shape: torch.Size([22, 6]), class range: 0.0-74.0


 60%|██████    | 3/5 [00:01<00:01,  1.74it/s]

Batch 3: targets shape: torch.Size([23, 6]), class range: 0.0-72.0


 80%|████████  | 4/5 [00:02<00:00,  1.75it/s]

Batch 4: targets shape: torch.Size([42, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.74it/s]


Epoch 49 average loss: 0.14037027955055237
Starting epoch 50


  0%|          | 0/5 [00:00<?, ?it/s]

Batch 0: targets shape: torch.Size([14, 6]), class range: 0.0-66.0


 20%|██        | 1/5 [00:00<00:02,  1.76it/s]

Batch 1: targets shape: torch.Size([57, 6]), class range: 0.0-75.0


 40%|████      | 2/5 [00:01<00:01,  1.77it/s]

Batch 2: targets shape: torch.Size([24, 6]), class range: 0.0-67.0


 60%|██████    | 3/5 [00:01<00:01,  1.77it/s]

Batch 3: targets shape: torch.Size([18, 6]), class range: 0.0-74.0


 80%|████████  | 4/5 [00:02<00:00,  1.77it/s]

Batch 4: targets shape: torch.Size([30, 6]), class range: 0.0-77.0


100%|██████████| 5/5 [00:02<00:00,  1.77it/s]


Epoch 50 average loss: 0.12992040812969208
---- Saving checkpoint to: './data/results/checkpoints/yolov3_ckpt_50.pth' ----


## Load adversarial trained model

In [12]:
if modelv == 3:
    model = load_model("./config/yolov3.cfg", f"./data/results/checkpoints/yolov3_ckpt_{epochs}.pth") # <- this assumes checkpoint interval is a factor of epochs
    # class_names = ['person', 'bicycle', 'car', 'motorbike', 'aeroplane', 'bus', 'train', 'truck', 'boat', 'traffic light', 'fire hydrant', 'stop sign', 'parking meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports ball', 'kite', 'baseball bat', 'baseball glove', 'skateboard', 'surfboard', 'tennis racket', 'bottle', 'wine glass', 'cup', 'fork', 'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake', 'chair', 'sofa', 'pottedplant', 'bed', 'diningtable', 'toilet', 'tvmonitor', 'laptop', 'mouse', 'remote', 'keyboard', 'cell phone', 'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy bear', 'hair drier', 'toothbrush']
    # id_list = np.array(range(0,90))
    root_train = "./data/COCO2017/images/train_sample"
    annFile_train = "./data/COCO2017/annotations/instances_train2017_modified_sample.json"
    root_val = "./data/COCO2017/images/valid_sample"
    annFile_val = "./data/COCO2017/annotations/instances_val2017_modified_sample.json"

else:
    print("invalid model number!")

# Attack Evaluation

In [13]:
# attackImage = 0 # variable for saving attack image, run this first, change pruning ratio (attack), 
# #don't run this and only run below cells

### NOTE: Attacker was defined here.

In [14]:
predictionsBefore = []
predictionsAfter = []
lossesBefore = []
lossesAfter = []
mode = "image" # need different modes if i want to save image or output prediction json
# mode = "json"
image_ids= [139, 285, 632, 724, 776, 785, 802, 872, 885, 1000,
            1268, 1296, 1353,1425, 1490, 1503, 1532, 1584, 1675, 1761]

os.makedirs("./data/results/images", exist_ok=True)

for i, (images, targets) in enumerate(tqdm(val_loader)):
    if targets[0].numel() != 0:
        with torch.no_grad():
            #* modify inputs to be in proper shape
            images = torch.stack(images) # images.shape is [n, 3, 416, 416] (even if n=1)
            images = images.to(device)
            image_id = int(targets[0][0,0].cpu().numpy()) # assume 1 image
            if image_id not in image_ids: continue # for when we want outputs of specific images
            for i, boxes in enumerate(targets): # targets is nx6, (image,class,x,y,w,h)
                if boxes.ndim == 2: boxes[:, 0] = i # change out image_id to id in batch to conform to compute_loss. this is normally done in ListDataset -> collate_fn. the id now starts at 0 for each image
            targets = torch.cat(targets, 0).to(device) # from tuples to one tensor
            # originalImageSize = targets[0, 6:].cpu().numpy() # original image shape, assume one image per batch - NOT available in json format
            img_info = coco_dataset_val.coco.imgs[image_id]
            originalImageSize = (img_info['height'], img_info['width'])
            targets = targets[:, :6]

            # print debugging information
            print(f"Image ID: {image_id}")
            print(f"Original targets shape: {targets.shape}")
            print(f"Targets data:")
            print(targets)
            print(f"Class indices: {targets[:, 1]}")
            print(f"Class range: {targets[:, 1].min()} - {targets[:, 1].max()}")

            # check mapping of class indices
            original_classes = targets[:, 1].clone()
            print(f"Original class IDs: {original_classes}")

            # mapping class indices ([1, 80] to [0, 79] range
            targets[:, 1] = targets[:, 1] - 1

            # verify mapped class indices
            mapped_classes = targets[:, 1]
            print(f"Mapped class IDs: {mapped_classes}")
            print(f"Mapped class range: {mapped_classes.min()} - {mapped_classes.max()}")

            # # ensure all classes are in range [0, 79]
            # valid_mask = (mapped_classes >= 0) & (mapped_classes < 80)
            # if not valid_mask.all():
            #     print(f"Invalid class indices found: {mapped_classes[~valid_mask]}")
            #     targets = targets[valid_mask]
            #     if targets.shape[0] == 0:
            #         print("No valid targets after filtering, skipping image")
            #         continue
            #     print(f"Filtered targets shape: {targets.shape}")

            # ensure all class indices are long
            targets[:, 1] = targets[:, 1].long()

            # final validation
            final_classes = targets[:, 1]
            print(f"Final class indices: {final_classes}")
            print(f"Final class range: {final_classes.min()} - {final_classes.max()}")
            print(f"All classes in range [0, 79]: {((final_classes >= 0) & (final_classes < 80)).all()}")

            #* loss
            model.train()
            try:
                outputsBefore = model(images)
                print(f"Model output shapes: {[out.shape for out in outputsBefore]}")

                lossBefore, loss_components = compute_loss(outputsBefore, targets, model)
                lossesBefore.append(lossBefore.cpu().numpy())

                images_adv = attacker.forward(images, targets) # get adversarial image

                outputsAfter = model(images_adv)
                lossAfter, loss_components = compute_loss(outputsAfter, targets, model)
                lossesAfter.append(lossAfter.cpu().numpy())

            except RuntimeError as e:
                print(f"CUDA error occurred: {e}")
                print(f"Error details:")
                print(f"  Targets shape: {targets.shape}")
                print(f"  Class indices: {targets[:, 1]}")
                # print(f"  Class unique values: {targets[:, 1].unique()}")
                print(f"  Class data type: {targets[:, 1].dtype}")

                # clean CUDA cache and skip this iteration
                torch.cuda.empty_cache()
                continue

            #* plot
            model.eval()

            # before attack
            outputsBefore = model(images[0].unsqueeze(0))
            boxesBefore = non_max_suppression(outputsBefore, conf_thres=0.3, iou_thres=0.5)[0].numpy()
            if mode == "json":
                boxesBefore = rescale_boxes(boxesBefore, img_size, originalImageSize)
            boxesBefore = nms2yolo(boxesBefore, images)
            if mode == "image":
                saveImageWithBoxes(images[0], boxesBefore, class_names, f"./data/results/images/attack_before_{image_id}.jpg")
            if mode == "json":
                predictionsBefore += yolo2json(boxesBefore, images[0].unsqueeze(0), image_id)

            # after attack
            outputsAfter = model(images_adv[0].unsqueeze(0))
            boxesAfter = non_max_suppression(outputsAfter, conf_thres=0.3, iou_thres=0.5)[0].numpy()

            if mode == "json":
                boxesAfter = rescale_boxes(boxesAfter, img_size, originalImageSize)
            boxesAfter = nms2yolo(boxesAfter, images_adv)
            print(boxesAfter)
            if mode == "image":
                saveImageWithBoxes(images_adv[0], boxesAfter, class_names, f"./data/results/images/attack_after_{image_id}.jpg")
            if mode == "json":
                predictionsAfter += yolo2json(boxesAfter, images_adv[0].unsqueeze(0), image_id)

    else: continue # pics without targets

with open(f'./data/results/predictionsBefore.json', 'w') as f:
    json.dump(predictionsBefore, f)
with open(f'./data/results/predictionsAfter.json', 'w') as f:
    json.dump(predictionsAfter, f)
np.savetxt("./data/results/lossesBefore.csv", lossesBefore, delimiter=",")
np.savetxt("./data/results/lossesAfter.csv", lossesAfter, delimiter=",")

  0%|          | 0/20 [00:00<?, ?it/s]

Image ID: 632
Original targets shape: torch.Size([18, 6])
Targets data:
tensor([[0.0000e+00, 5.9000e+01, 5.1094e-03, 5.3883e-01, 6.2692e-01, 3.2539e-01],
        [0.0000e+00, 5.8000e+01, 2.8650e-01, 3.3525e-01, 9.4969e-02, 1.4436e-01],
        [0.0000e+00, 7.3000e+01, 7.1247e-01, 4.2266e-01, 1.3391e-02, 5.5609e-02],
        [0.0000e+00, 7.3000e+01, 7.0830e-01, 5.1714e-01, 1.2531e-02, 5.3016e-02],
        [0.0000e+00, 7.3000e+01, 6.9494e-01, 5.8692e-01, 8.3125e-03, 6.2000e-02],
        [0.0000e+00, 7.3000e+01, 7.9055e-01, 4.2034e-01, 1.8984e-02, 5.7469e-02],
        [0.0000e+00, 7.3000e+01, 7.6173e-01, 4.3333e-01, 1.1687e-02, 4.3828e-02],
        [0.0000e+00, 5.6000e+01, 3.8253e-01, 4.8195e-01, 1.6363e-01, 1.3702e-01],
        [0.0000e+00, 5.8000e+01, 5.4273e-01, 4.5370e-01, 1.2892e-01, 2.2344e-01],
        [0.0000e+00, 7.3000e+01, 7.2017e-01, 4.2136e-01, 4.5828e-02, 5.6313e-02],
        [0.0000e+00, 7.3000e+01, 8.2347e-01, 5.1027e-01, 3.8125e-02, 6.3172e-02],
        [0.0000e+00, 7.300

  5%|▌         | 1/20 [00:00<00:08,  2.26it/s]

[[ 0.37976822  0.47996566  0.13524716  0.14167537  0.9421803  56.        ]
 [ 0.8248502   0.51418227  0.03856718  0.05951383  0.9231001  73.        ]
 [ 0.00950366  0.54514724  0.51569045  0.27680779  0.9089952  59.        ]
 [ 0.7193973   0.42094585  0.0404713   0.05487471  0.90326643 73.        ]
 [ 0.5455612   0.44884714  0.12155313  0.22413422  0.8282355  58.        ]
 [ 0.7898354   0.41942582  0.02557241  0.05730468  0.8028657  73.        ]
 [ 0.29206976  0.3338046   0.08850265  0.15719597  0.787224   58.        ]
 [ 0.64201844  0.1860417   0.20401548  0.4148546   0.5815011  73.        ]
 [ 0.7023448   0.42199665  0.02945445  0.05313287  0.54606456 73.        ]
 [ 0.70410055  0.51529145  0.01591066  0.04964359  0.34892783 73.        ]
 [ 0.7031663   0.49820217  0.03454707  0.04902737  0.34464204 73.        ]
 [ 0.7039118   0.43479064  0.01423014  0.04811874  0.30473477 73.        ]]
Image ID: 776
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[0.0000e+00, 7.7000e

 10%|█         | 2/20 [00:00<00:06,  2.85it/s]

[[ 0.31655508  0.0126345   0.4850785   0.8153185   0.927332   77.        ]
 [ 0.16703418  0.43086925  0.44608945  0.53349787  0.8066807  77.        ]
 [ 0.16163781  0.00729337  0.62562054  0.97057974  0.78597826 59.        ]
 [ 0.16969648  0.0926402   0.52564996  0.5531713   0.7674669  77.        ]]
Image ID: 285
Original targets shape: torch.Size([1, 6])
Targets data:
tensor([[ 0.0000, 21.0000,  0.0444,  0.1075,  0.9134,  0.8812]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([21.], device='cuda:0', dtype=torch.float64)
Class range: 21.0 - 21.0
Original class IDs: tensor([21.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([20.], device='cuda:0', dtype=torch.float64)
Mapped class range: 20.0 - 20.0
Final class indices: tensor([20.], device='cuda:0', dtype=torch.float64)
Final class range: 20.0 - 20.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.Size([1, 3, 26, 26, 85]), torch.Size([1, 3, 52, 52, 8

 15%|█▌        | 3/20 [00:00<00:05,  3.23it/s]

[[ 0.02743053  0.12211737  0.86899006  0.87836844  0.8715435  21.        ]]
Image ID: 1675
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[ 0.0000, 15.0000,  0.0000,  0.1469,  1.0000,  0.4587],
        [ 0.0000, 66.0000,  0.0961,  0.6997,  0.7938,  0.1652]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([15., 66.], device='cuda:0', dtype=torch.float64)
Class range: 15.0 - 66.0
Original class IDs: tensor([15., 66.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([14., 65.], device='cuda:0', dtype=torch.float64)
Mapped class range: 14.0 - 65.0
Final class indices: tensor([14., 65.], device='cuda:0', dtype=torch.float64)
Final class range: 14.0 - 65.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.Size([1, 3, 26, 26, 85]), torch.Size([1, 3, 52, 52, 85])]


 20%|██        | 4/20 [00:01<00:04,  3.45it/s]

[[ 0.01688422  0.13814782  0.76509124  0.49747843  0.92536306 15.        ]
 [ 0.09643849  0.6981407   0.62459904  0.1438741   0.3666961  66.        ]]
Image ID: 885
Original targets shape: torch.Size([9, 6])
Targets data:
tensor([[0.0000e+00, 0.0000e+00, 4.3330e-01, 4.6248e-01, 2.1889e-01, 3.2534e-01],
        [0.0000e+00, 0.0000e+00, 4.3909e-01, 3.0595e-01, 1.7473e-01, 2.6492e-01],
        [0.0000e+00, 0.0000e+00, 9.3075e-01, 2.0591e-01, 6.7766e-02, 3.5544e-01],
        [0.0000e+00, 0.0000e+00, 6.7922e-01, 1.6614e-01, 5.1234e-02, 1.9797e-02],
        [0.0000e+00, 0.0000e+00, 4.4905e-01, 1.6592e-01, 6.9766e-02, 1.7906e-02],
        [0.0000e+00, 3.8000e+01, 6.2506e-01, 5.8533e-01, 1.2709e-01, 6.2844e-02],
        [0.0000e+00, 0.0000e+00, 8.4669e-01, 1.6833e-01, 1.0287e-01, 1.5813e-02],
        [0.0000e+00, 0.0000e+00, 1.7344e-03, 1.6650e-01, 9.2094e-02, 1.3891e-02],
        [0.0000e+00, 0.0000e+00, 7.8042e-01, 1.6681e-01, 1.1745e-01, 2.0906e-02]],
       device='cuda:0', dtype=torch.flo

 25%|██▌       | 5/20 [00:01<00:04,  3.34it/s]

[[ 0.6220842   0.58588445  0.13196516  0.06736778  0.90608555 38.        ]
 [ 0.936803    0.20798972  0.08523647  0.31064084  0.9004809   0.        ]
 [ 0.4377095   0.30181968  0.16674973  0.30415437  0.8904176   0.        ]
 [ 0.43140814  0.4682732   0.21982971  0.3356418   0.8351432   0.        ]
 [ 0.68203586  0.16098629  0.05715253  0.03255437  0.82130957  0.        ]
 [ 0.77573764  0.16360496  0.06442686  0.02627219  0.43621123  0.        ]
 [ 0.44794467  0.16121557  0.06260006  0.02993118  0.35388494  0.        ]]
Image ID: 1000
Original targets shape: torch.Size([17, 6])
Targets data:
tensor([[0.0000e+00, 3.8000e+01, 7.3547e-02, 5.9873e-01, 7.4109e-02, 1.3644e-01],
        [0.0000e+00, 2.6000e+01, 3.2094e-02, 4.7923e-01, 8.3266e-02, 1.8989e-01],
        [0.0000e+00, 2.6000e+01, 3.0767e-01, 4.7555e-01, 1.0978e-01, 1.8367e-01],
        [0.0000e+00, 0.0000e+00, 1.7994e-01, 3.6270e-01, 1.3005e-01, 3.5689e-01],
        [0.0000e+00, 0.0000e+00, 6.3427e-01, 3.1316e-01, 5.8016e-02, 7.11

 30%|███       | 6/20 [00:01<00:04,  3.28it/s]

[[ 0.32833374  0.37690857  0.10138416  0.11501826  0.9430458  24.        ]
 [ 0.30569586  0.47380403  0.11076922  0.18471688  0.9302256  26.        ]
 [ 0.5210989   0.36125314  0.12478205  0.56293607  0.9180861   0.        ]
 [ 0.0723035   0.5976295   0.07635979  0.12010127  0.9157245  38.        ]
 [ 0.79062116  0.4322498   0.1845602   0.5138691   0.9066479   0.        ]
 [ 0.06722588  0.47400573  0.09119339  0.08827884  0.88891876 24.        ]
 [ 0.08431431  0.4134145   0.07248431  0.3401419   0.86310184  0.        ]
 [ 0.18196097  0.36462247  0.11713105  0.38491103  0.85612845  0.        ]
 [ 0.2865358   0.33887604  0.12606706  0.4436645   0.8280404   0.        ]
 [ 0.32417     0.39482027  0.14412841  0.42511413  0.795348    0.        ]
 [ 0.64174753  0.44258088  0.15632747  0.47622448  0.7639926   0.        ]
 [ 0.03277935  0.47667316  0.07624347  0.19401653  0.74824446 26.        ]
 [ 0.5932246   0.36995137  0.13225049  0.52116036  0.66446894  0.        ]
 [ 0.42158446  0.28081423

 35%|███▌      | 7/20 [00:02<00:03,  3.37it/s]

[[ 0.43325847  0.24359092  0.299288    0.5865757   0.8574659   0.        ]
 [ 0.32880828  0.7364323   0.64965236  0.0698116   0.7680703  30.        ]]
Image ID: 1503
Original targets shape: torch.Size([5, 6])
Targets data:
tensor([[0.0000e+00, 6.3000e+01, 1.6875e-03, 4.3681e-01, 3.9269e-01, 4.2472e-01],
        [0.0000e+00, 6.4000e+01, 3.7800e-01, 6.8116e-01, 1.1803e-01, 6.8937e-02],
        [0.0000e+00, 6.6000e+01, 5.0353e-01, 6.0138e-01, 4.8222e-01, 1.4225e-01],
        [0.0000e+00, 6.2000e+01, 3.9269e-01, 1.6081e-01, 3.4887e-01, 2.7978e-01],
        [0.0000e+00, 6.4000e+01, 9.5484e-01, 6.0747e-01, 4.5000e-02, 3.0188e-02]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([63., 64., 66., 62., 64.], device='cuda:0', dtype=torch.float64)
Class range: 62.0 - 66.0
Original class IDs: tensor([63., 64., 66., 62., 64.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([62., 63., 65., 61., 63.], device='cuda:0', dtype=torch.float64)
Mapped class range: 61.0 - 

 40%|████      | 8/20 [00:02<00:03,  3.34it/s]

[[ 0.49636045  0.60885143  0.5223149   0.12778722  0.8585146  66.        ]
 [ 0.00483418  0.44087988  0.46932378  0.40414095  0.8150688  63.        ]
 [ 0.39237344  0.16603796  0.3913526   0.3138641   0.8129688  62.        ]
 [ 0.9567576   0.6111263   0.05121099  0.0440921   0.7180933  64.        ]
 [ 0.37952372  0.684335    0.1166709   0.06010906  0.3403966  64.        ]
 [ 0.36282247  0.6773342   0.18481064  0.07866859  0.32100296 64.        ]]
Image ID: 1268
Original targets shape: torch.Size([11, 6])
Targets data:
tensor([[0.0000e+00, 1.4000e+01, 3.0127e-01, 5.1688e-01, 1.1677e-01, 5.2234e-02],
        [0.0000e+00, 8.0000e+00, 1.9495e-01, 3.6048e-01, 2.1803e-01, 2.6672e-02],
        [0.0000e+00, 8.0000e+00, 0.0000e+00, 3.6830e-01, 1.6475e-01, 2.3656e-02],
        [0.0000e+00, 0.0000e+00, 3.6359e-02, 4.9908e-01, 8.3641e-02, 1.0855e-01],
        [0.0000e+00, 0.0000e+00, 7.8387e-01, 2.8697e-01, 2.1613e-01, 5.3705e-01],
        [0.0000e+00, 0.0000e+00, 6.2866e-01, 4.8597e-01, 1.0197e-0

 45%|████▌     | 9/20 [00:02<00:03,  3.27it/s]

[[ 0.784377    0.28445387  0.2090862   0.55957186  0.9418284   0.        ]
 [ 0.02793561  0.4974623   0.09302151  0.10890484  0.89269817  0.        ]
 [ 0.03377361  0.5304087   0.0368626   0.08004152  0.8106544  24.        ]
 [ 0.29972368  0.5163041   0.10405388  0.06223517  0.75631857 14.        ]
 [ 0.03457659  0.5114543   0.05173743  0.08258137  0.526043   24.        ]
 [ 0.45462498  0.2983229   0.17614658  0.09620897  0.49390718  8.        ]
 [ 0.6231874   0.48392457  0.08135884  0.12973191  0.43240696  0.        ]
 [ 0.00348845  0.49276856  0.04393293  0.12397898  0.34589064  0.        ]]
Image ID: 802
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[ 0.0000, 72.0000,  0.5516,  0.2894,  0.2590,  0.5563],
        [ 0.0000, 69.0000,  0.2204,  0.4517,  0.1977,  0.3618]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([72., 69.], device='cuda:0', dtype=torch.float64)
Class range: 69.0 - 72.0
Original class IDs: tensor([72., 69.], device='cuda:0', d

 50%|█████     | 10/20 [00:03<00:02,  3.36it/s]

[[ 0.22450307  0.44644636  0.16682461  0.37147447  0.9348262  69.        ]
 [ 0.54949665  0.2874419   0.22060718  0.6020301   0.9312215  72.        ]
 [ 0.5499469   0.28778544  0.20885096  0.31387874  0.44455117 72.        ]]
Image ID: 1353
Original targets shape: torch.Size([7, 6])
Targets data:
tensor([[0.0000, 6.0000, 0.2566, 0.6472, 0.3798, 0.2786],
        [0.0000, 0.0000, 0.5532, 0.3090, 0.1330, 0.2582],
        [0.0000, 0.0000, 0.4218, 0.2730, 0.1510, 0.1052],
        [0.0000, 0.0000, 0.4012, 0.3962, 0.2561, 0.3691],
        [0.0000, 0.0000, 0.2482, 0.4277, 0.2334, 0.2858],
        [0.0000, 0.0000, 0.3919, 0.3611, 0.1521, 0.1454],
        [0.0000, 0.0000, 0.5013, 0.3656, 0.0640, 0.1255]], device='cuda:0',
       dtype=torch.float64)
Class indices: tensor([6., 0., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float64)
Class range: 0.0 - 6.0
Original class IDs: tensor([6., 0., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([ 5., -1., -1., -

 55%|█████▌    | 11/20 [00:03<00:02,  3.32it/s]

[[0.25732407 0.6500791  0.3095637  0.27616164 0.9730474  6.        ]
 [0.39404356 0.3435396  0.14810635 0.20340398 0.8514855  0.        ]
 [0.41324595 0.268393   0.14464349 0.17435867 0.7670927  0.        ]
 [0.5527123  0.31664196 0.13454005 0.2888554  0.69042486 0.        ]
 [0.4332553  0.2771432  0.11842999 0.11539349 0.63716173 0.        ]
 [0.24410072 0.4170742  0.21657634 0.2884793  0.5260512  0.        ]
 [0.39752373 0.39853385 0.20515047 0.31190878 0.47941187 0.        ]
 [0.5053316  0.36380464 0.09210087 0.15391666 0.4733365  0.        ]]
Image ID: 1490
Original targets shape: torch.Size([2, 6])
Targets data:
tensor([[0.0000e+00, 0.0000e+00, 7.0136e-01, 4.3806e-01, 7.9531e-02, 1.9192e-01],
        [0.0000e+00, 3.7000e+01, 5.6128e-01, 6.1295e-01, 3.4202e-01, 2.3484e-02]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([ 0., 37.], device='cuda:0', dtype=torch.float64)
Class range: 0.0 - 37.0
Original class IDs: tensor([ 0., 37.], device='cuda:0', dtype=torch.f

 60%|██████    | 12/20 [00:03<00:02,  3.30it/s]

[[0.69980556 0.44069672 0.074315   0.19243416 0.8862468  0.        ]]
Image ID: 724
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[ 0.0000, 11.0000,  0.3641,  0.1437,  0.2690,  0.3062],
        [ 0.0000,  7.0000,  0.3708,  0.5589,  0.0435,  0.0603],
        [ 0.0000,  2.0000,  0.3805,  0.5344,  0.0258,  0.0163],
        [ 0.0000, 11.0000,  0.5288,  0.5198,  0.0380,  0.0521]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([11.,  7.,  2., 11.], device='cuda:0', dtype=torch.float64)
Class range: 2.0 - 11.0
Original class IDs: tensor([11.,  7.,  2., 11.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([10.,  6.,  1., 10.], device='cuda:0', dtype=torch.float64)
Mapped class range: 1.0 - 10.0
Final class indices: tensor([10.,  6.,  1., 10.], device='cuda:0', dtype=torch.float64)
Final class range: 1.0 - 10.0
All classes in range [0, 79]: True
Model output shapes: [torch.Size([1, 3, 13, 13, 85]), torch.Size([1, 3, 26, 26, 85]), torch.Siz

 65%|██████▌   | 13/20 [00:03<00:02,  3.26it/s]

[[ 0.36878464  0.1445917   0.20355129  0.33494452  0.9474959  11.        ]
 [ 0.53031003  0.5200753   0.03970711  0.06270123  0.89562947 11.        ]
 [ 0.3676042   0.555482    0.05519632  0.0712303   0.816879    7.        ]
 [ 0.51301235  0.5050925   0.04290551  0.06663902  0.6220169  11.        ]
 [ 0.5441831   0.5247584   0.03967894  0.06772503  0.4067184  11.        ]
 [ 0.5112323   0.5203239   0.03422796  0.05106985  0.38394395 11.        ]]
Image ID: 1532
Original targets shape: torch.Size([8, 6])
Targets data:
tensor([[0.0000e+00, 2.0000e+00, 1.6875e-03, 7.0258e-01, 1.8539e-01, 1.6011e-01],
        [0.0000e+00, 2.0000e+00, 7.8359e-01, 7.4608e-01, 7.7875e-02, 7.1109e-02],
        [0.0000e+00, 2.0000e+00, 3.1341e-01, 7.5234e-01, 5.1016e-02, 4.0969e-02],
        [0.0000e+00, 2.0000e+00, 1.6592e-01, 7.1205e-01, 1.2358e-01, 9.3109e-02],
        [0.0000e+00, 7.0000e+00, 3.5245e-01, 7.3627e-01, 3.0672e-02, 2.4438e-02],
        [0.0000e+00, 2.0000e+00, 6.6616e-01, 7.4952e-01, 1.0042e-01

 70%|███████   | 14/20 [00:04<00:01,  3.25it/s]

[[0.00268396 0.7033299  0.13323177 0.1244589  0.97876966 2.        ]
 [0.16229916 0.70975804 0.13652618 0.08925966 0.9342439  2.        ]
 [0.34832728 0.6870401  0.22258693 0.16919954 0.85564643 2.        ]
 [0.6449328  0.7454714  0.09575272 0.08515152 0.82753193 2.        ]
 [0.32542482 0.74911714 0.07574587 0.06350796 0.79130673 2.        ]
 [0.00477267 0.70103633 0.23674013 0.15827325 0.75538015 2.        ]
 [0.78135514 0.7467635  0.08810087 0.08245527 0.65260035 2.        ]
 [0.625579   0.706797   0.1602292  0.12223581 0.5147867  2.        ]]
Image ID: 139
Original targets shape: torch.Size([20, 6])
Targets data:
tensor([[0.0000e+00, 5.8000e+01, 3.7028e-01, 3.8986e-01, 3.8594e-02, 1.0859e-01],
        [0.0000e+00, 6.2000e+01, 1.0984e-02, 4.2931e-01, 2.3331e-01, 1.4823e-01],
        [0.0000e+00, 6.2000e+01, 8.7064e-01, 4.9405e-01, 1.2711e-01, 1.2302e-01],
        [0.0000e+00, 5.6000e+01, 5.6091e-01, 5.0789e-01, 8.7500e-02, 1.6067e-01],
        [0.0000e+00, 5.6000e+01, 4.5420e-01, 5.

 75%|███████▌  | 15/20 [00:04<00:01,  3.23it/s]

[[ 0.87003016  0.4923234   0.12275857  0.11872673  0.9503425  62.        ]
 [ 0.45520365  0.50917125  0.118262    0.17434105  0.93194455 56.        ]
 [ 0.3707072   0.39248365  0.05447006  0.12875703  0.91274947 58.        ]
 [ 0.5138565   0.5229705   0.20587716  0.17253906  0.9011845  60.        ]
 [ 0.9546686   0.6489732   0.02740757  0.06280605  0.8954548  73.        ]
 [ 0.56360203  0.50662225  0.09200749  0.18167107  0.869177   56.        ]
 [ 0.86214435  0.6466378   0.06417113  0.14643064  0.833682   75.        ]
 [ 0.63834786  0.41138127  0.0740037   0.21048647  0.8098551   0.        ]
 [ 0.64783007  0.50950736  0.05647836  0.1271413   0.7667615  56.        ]
 [ 0.01584307  0.43089464  0.16257733  0.15982121  0.74234533 62.        ]
 [ 0.60011715  0.4316128   0.02860869  0.08814115  0.7121171   0.        ]
 [ 0.5842371   0.41419932  0.04998618  0.13982818  0.6483429   0.        ]
 [ 0.70170397  0.35572374  0.02307877  0.03538029  0.49200797 74.        ]
 [ 0.9355583   0.6486326 

 80%|████████  | 16/20 [00:04<00:01,  3.23it/s]

[[ 0.6311115   0.22038753  0.11698822  0.19448781  0.9801201  67.        ]
 [ 0.57646406  0.03372118  0.21475646  0.33511347  0.9111931   0.        ]
 [ 0.6328963   0.21771327  0.08555775  0.12012316  0.8736303  67.        ]
 [ 0.17163566  0.00809431  0.67592776  0.96217847  0.87007785  0.        ]
 [ 0.74427545  0.640536    0.03087146  0.02872658  0.63533276 74.        ]]
Image ID: 872
Original targets shape: torch.Size([4, 6])
Targets data:
tensor([[0.0000e+00, 3.2000e+01, 6.5161e-01, 2.6881e-01, 3.0281e-02, 2.5828e-02],
        [0.0000e+00, 0.0000e+00, 2.4103e-01, 1.5730e-01, 4.5617e-01, 7.1461e-01],
        [0.0000e+00, 0.0000e+00, 2.6989e-01, 1.9753e-01, 4.1514e-01, 7.5063e-01],
        [0.0000e+00, 3.5000e+01, 5.9006e-01, 2.4570e-01, 8.9766e-02, 7.1531e-02]],
       device='cuda:0', dtype=torch.float64)
Class indices: tensor([32.,  0.,  0., 35.], device='cuda:0', dtype=torch.float64)
Class range: 0.0 - 35.0
Original class IDs: tensor([32.,  0.,  0., 35.], device='cuda:0', dtype=t

 85%|████████▌ | 17/20 [00:05<00:00,  3.20it/s]

[[ 0.253566    0.1811394   0.3632269   0.7236484   0.93222284  0.        ]
 [ 0.5884444   0.24367628  0.09605742  0.06894192  0.85918343 35.        ]
 [ 0.6512759   0.27179217  0.04409511  0.0541073   0.6920027  32.        ]]
Image ID: 1584
Original targets shape: torch.Size([14, 6])
Targets data:
tensor([[0.0000, 5.0000, 0.2063, 0.1480, 0.6502, 0.7265],
        [0.0000, 0.0000, 0.3110, 0.4980, 0.0970, 0.1074],
        [0.0000, 0.0000, 0.7118, 0.5526, 0.0265, 0.0406],
        [0.0000, 0.0000, 0.4884, 0.5469, 0.0570, 0.0547],
        [0.0000, 0.0000, 0.2850, 0.2783, 0.0480, 0.0375],
        [0.0000, 0.0000, 0.4856, 0.2627, 0.0414, 0.0341],
        [0.0000, 0.0000, 0.1983, 0.6368, 0.0114, 0.0346],
        [0.0000, 5.0000, 0.9285, 0.5178, 0.0715, 0.1439],
        [0.0000, 0.0000, 0.1490, 0.6350, 0.0216, 0.0564],
        [0.0000, 0.0000, 0.3469, 0.2758, 0.0302, 0.0336],
        [0.0000, 0.0000, 0.1276, 0.6170, 0.0313, 0.0861],
        [0.0000, 0.0000, 0.1665, 0.6496, 0.0216, 0.0527],
     

 90%|█████████ | 18/20 [00:05<00:00,  3.21it/s]

[[0.19950148 0.13970383 0.5600002  0.7543317  0.940686   5.        ]
 [0.28154147 0.27954113 0.04164839 0.03529336 0.9142467  0.        ]
 [0.9288454  0.51400554 0.08641184 0.14145507 0.8833946  5.        ]
 [0.1443826  0.63565123 0.03659599 0.07468051 0.8775713  0.        ]
 [0.718267   0.54913545 0.02965957 0.04431072 0.8357621  0.        ]
 [0.8212233  0.5162297  0.1146431  0.11488907 0.82167745 5.        ]
 [0.3142555  0.49633646 0.09044354 0.10121456 0.7613961  0.        ]
 [0.6998554  0.5490173  0.03904431 0.04799689 0.52808005 0.        ]
 [0.18316863 0.64232147 0.04527921 0.08362656 0.48595884 0.        ]
 [0.294432   0.27926317 0.03902943 0.0325054  0.4440783  0.        ]
 [0.34900945 0.2776529  0.03553808 0.02926023 0.42488426 0.        ]
 [0.3112372  0.27850604 0.03909758 0.03056152 0.42045632 0.        ]
 [0.33363393 0.27723992 0.03959788 0.02853709 0.41133335 0.        ]
 [0.10271817 0.6050309  0.05448109 0.11646586 0.3455378  0.        ]
 [0.35423934 0.4947352  0.10774974

 95%|█████████▌| 19/20 [00:05<00:00,  3.30it/s]

[[ 0.09713034  0.39108866  0.55635124  0.3011656   0.9131742  48.        ]
 [ 0.759729    0.38759917  0.2172388   0.33945268  0.904367   45.        ]]
Image ID: 1761
Original targets shape: torch.Size([7, 6])
Targets data:
tensor([[0.0000, 4.0000, 0.6066, 0.2178, 0.0800, 0.0684],
        [0.0000, 4.0000, 0.4003, 0.0135, 0.1158, 0.1206],
        [0.0000, 0.0000, 0.1838, 0.9624, 0.0076, 0.0180],
        [0.0000, 0.0000, 0.1723, 0.9630, 0.0113, 0.0153],
        [0.0000, 0.0000, 0.1900, 0.9609, 0.0097, 0.0201],
        [0.0000, 0.0000, 0.2223, 0.9777, 0.0075, 0.0113],
        [0.0000, 0.0000, 0.1989, 0.9642, 0.0115, 0.0166]], device='cuda:0',
       dtype=torch.float64)
Class indices: tensor([4., 4., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float64)
Class range: 0.0 - 4.0
Original class IDs: tensor([4., 4., 0., 0., 0., 0., 0.], device='cuda:0', dtype=torch.float64)
Mapped class IDs: tensor([ 3.,  3., -1., -1., -1., -1., -1.], device='cuda:0',
       dtype=torch.float64)
Mapped cla

100%|██████████| 20/20 [00:06<00:00,  3.25it/s]

[[0.40255228 0.01569558 0.11315808 0.10740283 0.9258762  4.        ]
 [0.6072897  0.22203647 0.0883321  0.05923168 0.5765291  4.        ]
 [0.20052886 0.96454644 0.01223377 0.01354584 0.4014974  0.        ]
 [0.18328166 0.9641148  0.01267521 0.01316687 0.36110073 0.        ]]


In [15]:
# predictionsBefore = []
# predictionsAfter = []
# lossesBefore = []
# lossesAfter = []
# # mode = "image" # need different modes if i want to save image or output prediction json
# mode = "json"
# # image_ids= [71711,19221,22192] # output images that i want, 19221 is broccoli, 22192 is dog, 71711 is plane
# # image_ids= [139, 285, 632, 724, 776, 785, 802, 872, 885, 1000,
# #             1268, 1296, 1353,1425, 1490, 1503, 1532, 1584, 1675, 1761] # sample image id
# image_ids = [139]

# os.makedirs("./data/results/images", exist_ok=True)

# for i, (images, targets) in enumerate(tqdm(val_loader)):
#     if targets[0].numel() != 0:
#         with torch.no_grad():
#             #* modify inputs to be in proper shape
#             images = torch.stack(images) # images.shape is [n, 3, 416, 416] (even if n=1)
#             images = images.to(device)
#             image_id = int(targets[0][0,0].cpu().numpy()) # assume 1 image
#             if image_id not in image_ids: continue # for when we want outputs of specific images
#             for i, boxes in enumerate(targets): # targets is nx6, (image,class,x,y,w,h)
#                 if boxes.ndim == 2: boxes[:, 0] = i # change out image_id to id in batch to conform to compute_loss. this is normally done in ListDataset -> collate_fn. the id now starts at 0 for each image
#             targets = torch.cat(targets, 0).to(device) # from tuples to one tensor
#             # originalImageSize = targets[0, 6:].cpu().numpy() # original image shape, assume one image per batch - NOT available in json format
#             img_info = coco_dataset_val.coco.imgs[image_id]
#             originalImageSize = (img_info['height'], img_info['width'])
#             targets = targets[:, :6]

#             #* loss
#             model.train()
#             # start = time.time()
#             outputsBefore = model(images)
#             # end = time.time()
#             # print(end - start)
#             lossBefore, loss_components = compute_loss(outputsBefore, targets, model)
#             lossesBefore.append(lossBefore.cpu().numpy())

#             images_adv = attacker.forward(images, targets) # get adversarial image

#             outputsAfter = model(images_adv)
#             lossAfter, loss_components = compute_loss(outputsAfter, targets, model)
#             lossesAfter.append(lossAfter.cpu().numpy())

#             #* plot
#             model.eval()

#             # ground truth
#             # print(targets) #(ima ge,class,x,y,w,h), the class id starts from 1
#             # nms is (x1, y1, x2, y2, conf, cls), the class id starts from 0
#             # yolo is (x_center, y_center, width, height, conf. cls)

#             # before attack
#             outputsBefore = model(images[0].unsqueeze(0))
#             boxesBefore = non_max_suppression(outputsBefore, conf_thres=0.3, iou_thres=0.5)[0].numpy()
#             if mode == "json":
#                 boxesBefore = rescale_boxes(boxesBefore, img_size, originalImageSize)
#             boxesBefore = nms2yolo(boxesBefore, images)
#             if mode == "image":
#                 saveImageWithBoxes(images[0], boxesBefore, class_names, f"./data/results/images/attack_before_{image_id}.jpg")
#             if mode == "json":
#                 predictionsBefore += yolo2json(boxesBefore, images[0].unsqueeze(0), image_id)

#             # after attack
#             outputsAfter = model(images_adv[0].unsqueeze(0))
#             boxesAfter = non_max_suppression(outputsAfter, conf_thres=0.3, iou_thres=0.5)[0].numpy()


#             if mode == "json":
#                 boxesAfter = rescale_boxes(boxesAfter, img_size, originalImageSize)
#             # print(boxesAfter)
#             boxesAfter = nms2yolo(boxesAfter, images_adv)
#             print(boxesAfter)
#             if mode == "image":
#                 saveImageWithBoxes(images_adv[0], boxesAfter, class_names, f"./data/results/images/attack_after_{image_id}.jpg")

#                 # attackImage = images_adv[0] # for saving the same attack image for different pruning ratios, comment out after save
#                 # saveImageWithBoxes(attackImage, boxesAfter, class_names, f"./data/results/images/pruning/{image_id}/attack_after_99_x.jpg") # plot different pruning ratios with same attack image

#                 # greyscaleAttackImage = imgToGreyscale(attackImage)
#                 # saveImageWithBoxes(greyscaleAttackImage, boxesAfter, class_names, f"./data/results/images/pruning/{image_id}/attack_after_x_grey.jpg") # plot different pruning ratios with same attack image
#             if mode == "json":
#                 predictionsAfter += yolo2json(boxesAfter, images_adv[0].unsqueeze(0), image_id)
#             # time.sleep(0.1) # for using noise attack

#     else: continue # pics without targets
#     # break


# with open(f'./data/results/predictionsBefore.json', 'w') as f:
#     json.dump(predictionsBefore, f)
# with open(f'./data/results/predictionsAfter.json', 'w') as f:
#     json.dump(predictionsAfter, f)
# np.savetxt("./data/results/lossesBefore.csv", lossesBefore, delimiter=",")
# np.savetxt("./data/results/lossesAfter.csv", lossesAfter, delimiter=",")

In [16]:
# data = np.loadtxt('./data/results/lossesBefore.csv', delimiter=',')
# average = np.mean(data)
# print("Avg loss before attack:", average)
# data = np.loadtxt('./data/results/lossesAfter.csv', delimiter=',')
# average = np.mean(data)
# print("Avg loss after attack:", average)

# Get mAP

In [17]:
# from pycocotools.coco import COCO
# from pycocotools.cocoeval import COCOeval

# coco_gld = COCO(annFile_val) # coco
# # if modelv == 2:
# #     coco_rst = coco_gld.loadRes('./data/results/v2predictions.json')
# # elif modelv == 3:
# #     coco_rst = coco_gld.loadRes('./data/results/v3predictions.json')

# coco_rst = coco_gld.loadRes('./data/results/predictionsAfter.json')
# cocoEval = COCOeval(coco_gld, coco_rst, iouType='bbox')
# cocoEval.evaluate()
# cocoEval.accumulate()
# cocoEval.summarize()